/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxCcu6_reg.h"
#include "IfxVadc_reg.h"

// Port Registers
#define PC1_BIT_LSB_IDX   11
#define PC2_BIT_LSB_IDX   19
#define PC3_BIT_LSB_IDX   27
#define PC5_BIT_LSB_IDX   11
#define PC7_BIT_LSB_IDX   27
#define P1_BIT_LSB_IDX    1
#define P2_BIT_LSB_IDX    2
#define P3_BIT_LSB_IDX    3
#define P5_BIT_LSB_IDX    5
#define P7_BIT_LSB_IDX    7


// SCU Registers
#define LCK_BIT_LSB_IDX   1
#define ENDINIT_BIT_LSB_IDX 0
#define EXIS0_BIT_LSB_IDX 4
#define FEN0_BIT_LSB_IDX  8
#define REN0_BIT_LSB_IDX  9
#define EIEN0_BIT_LSB_IDX 11
#define INP0_BIT_LSB_IDX  12
#define IGP0_BIT_LSB_IDX  14

// SRC Registers
#define SRPN_BIT_LSB_IDX  0
#define TOS_BIT_LSB_IDX   11
#define SRE_BIT_LSB_IDX   10

// CCU60 Registers
#define DISS_BIT_LSB_IDX  1
#define DISR_BIT_LSB_IDX  0
#define CTM_BIT_LSB_IDX   7
#define T12PRE_BIT_LSB_IDX 3
#define T12CLK_BIT_LSB_IDX 0
#define T12STR_BIT_LSB_IDX 6
#define T12RS_BIT_LSB_IDX  1
#define INPT12_BIT_LSB_IDX 10
#define ENT12PM_BIT_LSB_IDX 7

#define SRPN_BIT_LSB_IDX   0
#define TOS_BIT_LSB_IDX    11
#define SRE_BIT_LSB_IDX    10


void initRGBLED(void)
{
    // Reset Port_IOCR register
    P02_IOCR4.U &= ~(0x1F << PC7_BIT_LSB_IDX); // P02 -> IOCR4 - > PC7
    P10_IOCR4.U &= ~(0x1F << PC5_BIT_LSB_IDX); // P10 -> IOCR4 -> PC5
    P10_IOCR0.U &= ~(0x1F << PC3_BIT_LSB_IDX); // P10 -> IOCR0 -> PC3

    // Set Port as general purpose output
    P02_IOCR4.U |= 0x10 << PC7_BIT_LSB_IDX;
    P10_IOCR4.U |= 0x10 << PC5_BIT_LSB_IDX;
    P10_IOCR0.U |= 0x10 << PC3_BIT_LSB_IDX;
}

void initLED(void)
{
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX); // reset P10_IOCR0 PC1
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX); // reset P10_IOCR0 PC2
    P10_IOCR0.U |= 0x10 << PC1_BIT_LSB_IDX;    // set P10.1 push-pull general output
    P10_IOCR0.U |= 0x10 << PC2_BIT_LSB_IDX;    // set P10.2 push-pull general output
}

void initButton(void)
{
    P02_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);
    P02_IOCR0.U |= 0x02 << PC1_BIT_LSB_IDX;

}

void initERU(void)
{
    // ERS2 -> EXIS0 -> P02.1 Pin Selection
    SCU_EICR1.U &= ~(0x7 << EXIS0_BIT_LSB_IDX);
    SCU_EICR1.U |= 0x1 << EXIS0_BIT_LSB_IDX;

    // ETL -> EXIS0 -> Falling Edge & Trigger Enable
    SCU_EICR1.U |= 0x1 << FEN0_BIT_LSB_IDX;
    SCU_EICR1.U |= 0x1 << REN0_BIT_LSB_IDX;

    SCU_EICR1.U |= 0x1 << EIEN0_BIT_LSB_IDX;

    // ERS2 -> INP0 -> OCU0 Setting
    SCU_EICR1.U &= ~(0x7 << INP0_BIT_LSB_IDX);

    // OGU0 -> IGCR -> IGP0 Setting
    SCU_IGCR0.U &= ~(0x3 << IGP0_BIT_LSB_IDX);

    SCU_IGCR0.U |= 0x1 << IGP0_BIT_LSB_IDX;

    // SRC Interrupt Setting
    SRC_SCU_SCU_ERU0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_SCU_SCU_ERU0.U |= 0x0A << SRPN_BIT_LSB_IDX;

    SRC_SCU_SCU_ERU0.U &= ~(0x3 << TOS_BIT_LSB_IDX);

    SRC_SCU_SCU_ERU0.U |= 1 << SRE_BIT_LSB_IDX;
}

void initCCU60(void)
{
    // Password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);

    // Modify Access to clear ENDINIT
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) & ~(1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

    // Enable CCY
    CCU60_CLC.U &= ~(1<<DISR_BIT_LSB_IDX);

    // Password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);

    // Modify Access to set ENDINIT
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

    // CCU60 T12 configurations
    while(CCU60_CLC.U & (1 << DISS_BIT_LSB_IDX) != 0);

    CCU60_TCTR0.U &= ~(0x7 << T12CLK_BIT_LSB_IDX);
    CCU60_TCTR0.U |= 0x2 << T12CLK_BIT_LSB_IDX;
    CCU60_TCTR0.U |= 0x1 << T12PRE_BIT_LSB_IDX;

    CCU60_TCTR0.U &= ~(0x1 << CTM_BIT_LSB_IDX);

    // interrupt per 1 sec
    CCU60_T12PR.U = 24414-1;  //(48828Hz / 2) - 1

    // Set Shadow value to Period Register
    CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;

    // Clear T12 counter register
    CCU60_T12.U = 0;

    CCU60_INP.U &= ~(0x3 << INPT12_BIT_LSB_IDX);
    CCU60_IEN.U |= 0x1 << ENT12PM_BIT_LSB_IDX; // Enable T12 interrupt


    //SRC setting for CCU60
    SRC_CCU6_CCU60_SR0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_CCU6_CCU60_SR0.U |= 0x0B << SRPN_BIT_LSB_IDX;

    SRC_CCU6_CCU60_SR0.U &= ~(0x3 << TOS_BIT_LSB_IDX);

    SRC_CCU6_CCU60_SR0.U |= 0x1 << SRE_BIT_LSB_IDX;

    // CCU60 T12 Counting start
    CCU60_TCTR4.U = 0x1 << T12RS_BIT_LSB_IDX;

}




__interrupt(0x0B) __vector_table(0)
void CCU60_T12_ISR(void)
{
    P10_OUT.U ^= 0x1 << P2_BIT_LSB_IDX;
}

/*
__interrupt(0x0A) __vector_table(0)
void ERU0_ISR(void)
{
        P10_OUT.B.P1 = 0x1;
        for (unsigned int i = 0; i < 100000; i++);
        P10_OUT.B.P1 = 0x0;
        CCU60_T12PR.U = (int) 48828/(number+1)-1;
        CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;
        number += 1;
        number %= 5;
}
*/

__interrupt(0x0A) __vector_table(0)
void ERU0_ISR(void)
{
        if((P02_IN.U & (0x1 << P1_BIT_LSB_IDX)) == 0)
        {
            P10_OUT.B.P1 = 0x1;
            CCU60_T12PR.U = 12207-1;
            CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;
        }
        else
        {
            P10_OUT.B.P1 = 0x0;
            CCU60_T12PR.U = 24414-1;
            CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;
        }
}



IfxCpu_syncEvent g_cpuSyncEvent = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    //initERU();
    //initCCU60();
    initLED();
    initRGBLED();
    //initButton();



    while(1)
    {
        for(unsigned int i = 0; i < 1000000; i++);
        P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
        P10_OUT.U |= 0x1 << P5_BIT_LSB_IDX;
        P10_OUT.U |= 0x1 << P3_BIT_LSB_IDX;

        for(unsigned int i = 0; i < 1000000; i++);
        P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
        P10_OUT.U |= 0x1 << P5_BIT_LSB_IDX;
        P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);

        for(unsigned int i = 0; i < 1000000; i++);
        P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
        P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
        P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);

        for(unsigned int i = 0; i < 1000000; i++);
        P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
        P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
        P10_OUT.U |= 0x1 << P3_BIT_LSB_IDX;

    }

    return (1);
}
