/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#define PC0_BIT_LSB_IDX 3
#define PC1_BIT_LSB_IDX 11
#define PC2_BIT_LSB_IDX 19
#define P0_BIT_LSB_IDX 0
#define P1_BIT_LSB_IDX 1
#define P2_BIT_LSB_IDX 2
#define EXIS0_BIT_LSB_IDX 4
#define EXIS1_BIT_LSB_IDX 20
#define FEN0_BIT_LSB_IDX 8
#define FEN1_BIT_LSB_IDX 24
#define REN0_BIT_LSB_IDX 9
#define REN1_BIT_LSB_IDX 25
#define EIEN0_BIT_LSB_IDX 11
#define EIEN1_BIT_LSB_IDX 27
#define INP0_BIT_LSB_IDX 12
#define INP1_BIT_LSB_IDX 28
#define IGP0_BIT_LSB_IDX 14
#define IGP1_BIT_LSB_IDX 30
#define SRPN_BIT_LSB_IDX 0
#define TOS_BIT_LSB_IDX 11
#define SRE_BIT_LSB_IDX 10

void initERU(void) {
    // LED RED
    // ERU setting
    SCU_EICR1.U &= ~(0x7 << EXIS0_BIT_LSB_IDX);  // external interrupt to switch D3 pin
    SCU_EICR1.U |= (0x1 << EXIS0_BIT_LSB_IDX);

    SCU_EICR1.U |= 0x1 << FEN0_BIT_LSB_IDX; // detecting falling edge
    // Lab2 : Detecting rising edge
    //SCU_EICR1.U |= 0x1 << REN0_BIT_LSB_IDX;

    SCU_EICR1.U |= 0x1 << EIEN0_BIT_LSB_IDX; // enabling external input trigger event

    SCU_EICR1.U &= ~(0x7 << INP0_BIT_LSB_IDX); // setting output channel as OGU0

    SCU_IGCR0.U &= ~(0x3 << IGP0_BIT_LSB_IDX); // bypassing event trigger through OGU0
    SCU_IGCR0.U |= 0x1 << IGP0_BIT_LSB_IDX;

    // SRC Interrupt setting
    SRC_SCU_SCU_ERU0.U &= ~(0xFF << SRPN_BIT_LSB_IDX); // service request number; higher the value, higher the priority
    SRC_SCU_SCU_ERU0.U |= 0x0A << SRPN_BIT_LSB_IDX;
    SRC_SCU_SCU_ERU0.U &= ~(0x3 << TOS_BIT_LSB_IDX); // initializing service for CPU0
    SRC_SCU_SCU_ERU0.U |= 0x1 << SRE_BIT_LSB_IDX; // final request enabling, should set to 1 at final step
}

/*
void initERU1(void) {

    // LED BLUE
    SCU_EICR1.U &= ~(0x7 << EXIS1_BIT_LSB_IDX);
    SCU_EICR1.U &= (0x2 << EXIS1_BIT_LSB_IDX);

    SCU_EICR1.U |= 0x1 << FEN1_BIT_LSB_IDX;
    SCU_EICR1.U |= 0x1 << EIEN1_BIT_LSB_IDX;

    SCU_EICR1.U &= ~(0x7 << INP1_BIT_LSB_IDX); // setting output channel as OGU1
    SCU_EICR1.U |= (0x1 << INP1_BIT_LSB_IDX);

    SCU_IGCR0.U &= ~(0x3 << IGP1_BIT_LSB_IDX);
    SCU_IGCR0.U |= 0x1 << IGP1_BIT_LSB_IDX;

    SRC_SCU_SCU_ERU1.U &= ~(0xFF << SRPN_BIT_LSB_IDX); // service request number; higher the value, higher the priority
    SRC_SCU_SCU_ERU1.U |= 0x0B << SRPN_BIT_LSB_IDX;
    SRC_SCU_SCU_ERU1.U &= ~(0x3 << TOS_BIT_LSB_IDX);
    SRC_SCU_SCU_ERU1.U |= 0x1 << SRE_BIT_LSB_IDX;
}
*/

void initLED(void) {
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX); // reset P10_IOCR0 PC1
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX); // reset P10_IOCR0 PC2

    P10_IOCR0.U |= 0x10 << PC1_BIT_LSB_IDX; // set P10.1 push-pull general output
    P10_IOCR0.U |= 0x10 << PC2_BIT_LSB_IDX; // set P10.2 push-pull general output
}

void initButton(void) {
    P02_IOCR0.U &= ~(0X1F << PC1_BIT_LSB_IDX);
    P02_IOCR0.U &= ~(0X1F << PC0_BIT_LSB_IDX);

    P02_IOCR0.U |= 0x02 << PC1_BIT_LSB_IDX;
    P02_IOCR0.U |= 0x02 << PC0_BIT_LSB_IDX;
}

__interrupt(0x0A) __vector_table(0)
void ERU0_ISR(void) {
    P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX; // toggle P10.1 (LED D12 RED)

    // Lab1 : LED pulse
    /*
    P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX;
    for(int i = 0; i < 100000; i++);
    P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX;
    */

    // Lab3 : LED toggle with delay
    /*
    unsigned char a = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(int i = 0; i < 10000000; i++);
    unsigned char b = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(int i = 0; i < 10000000; i++);
    unsigned char c = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(int i = 0; i < 10000000; i++);

    if(a == 0 && b == 0 && c == 0)
        P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX;
    */
}

__interrupt(0x0B) __vector_table(0)
void ERU1_ISR(void) {
    P10_OUT.U ^= 0x1 << P2_BIT_LSB_IDX; // toggle P10.1 (LED D12 RED)
}

IfxCpu_syncEvent g_cpuSyncEvent = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    initERU();
    //initERU1();
    initLED();
    initButton();

    while(1) {
    }
    return (1);
}
