/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

// Port registers
#define PC1_BIT_LSB_IDX 11
#define PC2_BIT_LSB_IDX 19
#define P1_BIT_LSB_IDX 1
#define P2_BIT_LSB_IDX 2

// SCU registers
#define EXIS0_BIT_LSB_IDX 4
#define FEN0_BIT_LSB_IDX 8
#define REN0_BIT_LSB_IDX 9
#define EIEN0_BIT_LSB_IDX 11
#define INP0_BIT_LSB_IDX 12
#define IGP0_BIT_LSB_IDX 14

// SRC registers
#define SRPN_BIT_LSB_IDX 0
#define TOS_BIT_LSB_IDX 11
#define SRE_BIT_LSB_IDX 10


IfxCpu_syncEvent g_cpuSyncEvent = 0;

__interrupt(0x0A) __vector_table(0) // interrupt ID = 0x0A, CPU # = 0
void ERU0_ISR(void){
    /*
    // Lab1,2
    P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX;         // Set P10.1 (LED D12 RED)
    for(unsigned int i=0 ; i < 300000; i++);
    P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX);      // Clear P10.1 (LED D12 RED)
     */

    // Lab 3
    unsigned char t1 = P02_IN.U &(0x1 << P1_BIT_LSB_IDX);
    for(unsigned int i=0; i<10000000; i++);    // SW delay

    unsigned char t2 = P02_IN.U &(0x1 << P1_BIT_LSB_IDX);
    for(unsigned int i=0; i<10000000; i++);    // SW delay

    unsigned char t3 = P02_IN.U &(0x1 << P1_BIT_LSB_IDX);
    for(unsigned int i=0; i<10000000; i++);    // SW delay

    if (t1==0 && t2==0 && t3==0){
        P10_OUT.U |= 0x1 << P1_BIT_LSB_IDX;     // set p10.1 (LED D13 RED)
        for(unsigned int i=0; i<50000000; i++);
        P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX);     // clear p10.1 (LED D13 RED)

    }
}


void initERU(void){
    // 1) ERU setting : P02.1 pin(switch 03) selection
    // EICR1 -> ERS2 -> PO2.1 access
    // Set switch for checking switch is pressed or not
    SCU_EICR1.U &= ~(0X7 << EXIS0_BIT_LSB_IDX);
    SCU_EICR1.U |= (0X1 << EXIS0_BIT_LSB_IDX);

    // 2) Set for collecting switch trigger event
    // It was supposed to be masked before setting but 0x1 doesn't have to
    SCU_EICR1.U |= (0X1 << FEN0_BIT_LSB_IDX);       // falling edge

//    SCU_EICR1.U |= (0X1 << REN0_BIT_LSB_IDX);       // rising edge
    SCU_EICR1.U |= (0X1 << EIEN0_BIT_LSB_IDX);

    // 3) Send output to OGU
    SCU_EICR1.U &= ~(0X7 << INP0_BIT_LSB_IDX);

    // 4) Response trigger event to output
    SCU_IGCR0.U &= ~(0X3 << IGP0_BIT_LSB_IDX);
    SCU_IGCR0.U |= (0X1 << IGP0_BIT_LSB_IDX);

    // 5) SRC interrupt setting
    SRC_SCU_SCU_ERU0.U &= ~(0Xff << SRPN_BIT_LSB_IDX);
    SRC_SCU_SCU_ERU0.U |= (0X0A << SRPN_BIT_LSB_IDX);

    SRC_SCU_SCU_ERU0.U &= ~(0X3 << TOS_BIT_LSB_IDX);
    SRC_SCU_SCU_ERU0.U |= 1 << SRE_BIT_LSB_IDX;
}

void initButton(void){
    P02_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);  // reset to zero
    P02_IOCR0.U |= 0x02 << PC1_BIT_LSB_IDX;     // set p02.1 general input (pull-up connected)
}

void initLED(void){
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);  // reset to zero
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX);  // reset to zero

    P10_IOCR0.U |= 0x10 << PC1_BIT_LSB_IDX;  // set to p10.1 push-pull general output
    P10_IOCR0.U |= 0x10 << PC2_BIT_LSB_IDX;  // set to p10.2 push-pull general output
}


int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    initERU();
    initLED();
    initButton();

    while(1)
    {
        /*
        // 1. GPIO OUT
        for(uint32 i=0; i<1000000; i++);    // SW delay

        P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX; // toggle P10.1(LED D12 RED)

        for(uint32 i=0; i<1000000; i++);    // SW delay

        P10_OUT.U ^= 0x1 << P2_BIT_LSB_IDX; // toggle P10.2(LED D13 BLUE)
        */

        /*
        // 2. GPIO IN
        if((P02_IN.U &(0x1 << P1_BIT_LSB_IDX)) == 0){ // check button status, is it pushed?
            P10_OUT.U |= 0x1 << P1_BIT_LSB_IDX;     // set p10.1 (LED D13 RED)
        }
        else{
            P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX); // clear p10.1 (LED D13 RED)
        }
        */

        /*
        // 3. Sampling GPIO IN
        unsigned char t1 = P02_IN.U &(0x1 << P1_BIT_LSB_IDX);
        for(uint32 i=0; i<10000000; i++);    // SW delay

        unsigned char t2 = P02_IN.U &(0x1 << P1_BIT_LSB_IDX);
        for(uint32 i=0; i<10000; i++);    // SW delay

        unsigned char t3 = P02_IN.U &(0x1 << P1_BIT_LSB_IDX);
        for(uint32 i=0; i<10000; i++);    // SW delay

        if (t1==0 && t2==0 && t3==0){
            P10_OUT.U |= 0x1 << P1_BIT_LSB_IDX;     // set p10.1 (LED D13 RED)
        }
        else{
            P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX); // clear p10.1 (LED D13 RED)
        }
        */

        /*
        // 4. Polling based edge detection
        unsigned char pre = P02_IN.U &(0x1 << P1_BIT_LSB_IDX);
        for(uint32 i=0; i<1000; i++);    // SW delay
        unsigned char cur = P02_IN.U &(0x1 << P1_BIT_LSB_IDX);

        if (pre ^ cur){
            P10_OUT.U |= 0x1 << P1_BIT_LSB_IDX;     // set p10.1 (LED D13 RED)
            for(uint32 i=0; i<10000; i++);    // SW delay
            P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX);     // clear p10.1 (LED D13 RED)
        }
        */

    }
    return (1);
}
