/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "Cpu0_Main.h"


IfxCpu_syncEvent g_cpuSyncEvent = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    //initCCU60();
    //initERU();
    //init_LED();
    //init_Button();
    init_LED_PWM();
    initRGBLED();
    initVADC();
    initGTM();

    unsigned int adcResult;

    GTM_TOM0_TGC0_GLB_CTRL.B.HOST_TRIG = 1; // PWM 신호 발생 트리거
    GTM_TOM0_TGC1_GLB_CTRL.B.HOST_TRIG = 1;

    while(1)
    {
        VADC_startConversion();
        adcResult = VADC_readResult();

        GTM_TOM0_CH2_SR1.U = (adcResult/4096.0f) * 12500 - 1;
        GTM_TOM0_CH3_SR1.U = (adcResult/4096.0f) * 12500 - 1;
        GTM_TOM0_CH15_SR1.U = (adcResult/4096.0f) * 12500 - 1;

    }
    return (1);
}

#if 0
P02_IN.B.P1 == 0 // 3번 스위치
P02_IN.B.P0 == 0   // 2번 스위치

P10_OUT.B.P1 = 1;   // 빨간 LED
P10_OUT.B.P2 = 1;   //파란 LED

P02_OUT.B.P7 = 1; // Red
P10_OUT.B.P5 = 0; // Green
P10_OUT.B.P3 = 0; // Blue\

GTM_TOM0_CH1_SR1.U = 1000; // PWM 듀티 설정
#endif




