/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxCcu6_reg.h"
#include "IfxVadc_reg.h"
#include "IfxGtm_reg.h"

#define LAB 2

// PORT REGISTERS
#define PC1_BIT_LSB_IDX 11
#define PC2_BIT_LSB_IDX 19
#define P1_BIT_LSB_IDX 1
#define P2_BIT_LSB_IDX 2

#define PC7_BIT_LSB_IDX 27
#define PC5_BIT_LSB_IDX 11
#define PC3_BIT_LSB_IDX 27
#define P7_BIT_LSB_IDX 7
#define P5_BIT_LSB_IDX 5
#define P3_BIT_LSB_IDX 3


// SCU REGISTERS
#define EXIS0_BIT_LSB_IDX 4
#define FEN0_BIT_LSB_IDX 8
#define REN0_BIT_LSB_IDX 9
#define EIEN0_BIT_LSB_IDX 11
#define INP0_BIT_LSB_IDX 12
#define IGP0_BIT_LSB_IDX 14

#define LCK_BIT_LSB_IDX 1
#define ENDINIT_BIT_LSB_IDX 0

// SRC REGISTERS
#define SRPN_BIT_LSB_IDX 0
#define TOS_BIT_LSB_IDX 11
#define SRE_BIT_LSB_IDX 10

// CCU60 registers
#define DISS_BIT_LSB_IDX 1
#define DISR_BIT_LSB_IDX 0
#define CTM_BIT_LSB_IDX 7
#define T12PRE_BIT_LSB_IDX 3
#define T12CLK_BIT_LSB_IDX 0
#define T12STR_BIT_LSB_IDX 6
#define T12RS_BIT_LSB_IDX 1
#define INPT12_BIT_LSB_IDX 10
#define ENT12PM_BIT_LSB_IDX 7

// VADC registers
#define ANONC_BIT_LSB_IDX 0
#define ASEN0_BIT_LSB_IDX 24
#define CSM0_BIT_LSB_IDX 3
#define PRIO0_BIT_LSB_IDX 0
#define CMS_BIT_LSB_IDX 8
#define FLUSH_BIT_LSB_IDX 10
#define TREV_BIT_LSB_IDX 9
#define ENGT_BIT_LSB_IDX 0
#define RESPOS_BIT_LSB_IDX 21
#define RESREG_BIT_LSB_IDX 16
#define ICLSEL_BIT_LSB_IDX 0
#define VF_BIT_LSB_IDX 31
#define RESULT_BIT_LSB_IDX 0
#define ASSCH7_BIT_LSB_IDX 7

// GTM registers
#define SEL7_BIT_LSB_IDX        14
#define SEL11_BIT_LSB_IDX       22
#define SEL9_BIT_LSB_IDX        18
#define EN_FXCLK_BIT_LSB_IDX    22
#define FXCLK_SEL_BIT_LSB_IDX   0

// GTM - TOM0 registers
#define UPEN_CTRL1_BIT_LSB_IDX  18
#define HOST_TRIG_BIT_LSB_IDX   0
#define ENDIS_CTRL1_BIT_LSB_IDX 2
#define OUTEN_CTRL1_BIT_LSB_IDX 2
#define CLK_SRC_SR_BIT_LSB_IDX  12
#define OSM_BIT_LSB_IDX         26
#define TRIGOUT_BIT_LSB_IDX     24
#define SL_BIT_LSB_IDX          11

IfxCpu_syncEvent g_cpuSyncEvent = 0;

 void clearLock(void)
 {
     // Password Access to unlock SCU_WDTSCON0
     SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0XFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
     while ((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0); // wait until unlocked

     // Modify Access to clear ENDINIT : clear와 동시에 lock 걸기
     SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0XFC) | (1 << LCK_BIT_LSB_IDX)) & ~(1 << ENDINIT_BIT_LSB_IDX);
     while ((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0); // wait until locked
 }

 void setLock(void)
 {
     // Password Access to unlock SCU_WDTSCON0
     SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0XFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
     while ((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0); // wait until unlocked

     // Modify Access to SET ENDINIT : clear와 동시에 lock 걸기
     SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0XFC) | (1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
     while ((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0); // wait until locked
 }

 void VADC_startConversion(void)
 {
     VADC_G4_QINR0.U |= 0x07;                            // no. of Request Channel = 7
     VADC_G4_QMR0.U |= 0x1 << TREV_BIT_LSB_IDX;          // Generate Conversion Start Trigger Event
 }

 unsigned int VADC_readResult(void)
 {
     unsigned int result;

     while ((VADC_G4_RES0.U & (0x1 << VF_BIT_LSB_IDX)) == 0);    // wait until read available
     result = VADC_G4_RES0.U & (0xFFF << RESULT_BIT_LSB_IDX);    // read ADC value

     return result;
 }

void initGTM(void)
{
#if (LAB == 1)
    clearLock();

    GTM_CLC.U &= ~(1 << DISR_BIT_LSB_IDX);                          // enable GTM

    setLock();

    while ((GTM_CLC.U & (1 << DISS_BIT_LSB_IDX)) != 0);             // wait until GTM module enabled

    // 설정을 한 다음에 enable 시킴, clock 선택 후 gate열어주기 (glitch 발생의 위험 때문에)
    // GTM clock configuration
    GTM_CMU_FXCLK_CTRL.U &= ~(0xF << FXCLK_SEL_BIT_LSB_IDX);        // input clock of CMU FXCLK --< CMU GCLK EN
    GTM_CMU_CLK_EN.U |= 0x2 << EN_FXCLK_BIT_LSB_IDX;                // enable all CMU_FXCLK

    // GTM TOM0 PWM configuration
    GTM_TOM0_TGC0_GLB_CTRL.U |= 0x2 << UPEN_CTRL1_BIT_LSB_IDX;      // TOM channel 1 update enable

    GTM_TOM0_TGC0_ENDIS_CTRL.U |= 0x2 << ENDIS_CTRL1_BIT_LSB_IDX;   // enable channel 1 on update trigger

    GTM_TOM0_TGC0_OUTEN_CTRL.U |= 0x2 << OUTEN_CTRL1_BIT_LSB_IDX;   // enable channel 1 on output trigger

    GTM_TOM0_CH1_CTRL.U |= 0x1 << SL_BIT_LSB_IDX;                   // high signal level for duty cycle
    GTM_TOM0_CH1_CTRL.U |= 0x1 << CLK_SRC_SR_BIT_LSB_IDX;           // clock source --> CMU_FXCLK(1) = 6250(HZ)
    GTM_TOM0_CH1_CTRL.U &= ~(0x1 << OSM_BIT_LSB_IDX);               // continuous ode enable
    GTM_TOM0_CH1_CTRL.U &= ~(0x1 << TRIGOUT_BIT_LSB_IDX);           // TRIG[x] = TRIG[x - 1]

    GTM_TOM0_CH1_SR0.U = 12500 - 1;                                 // PWM freq. = 6250 Hz / 12500 = 500 Hz

    GTM_TOM0_CH1_SR1.U = 1250 - 1;                                  // duty cycle = 1250 / 12500 = 10 % (temporary)

    GTM_TOUTSEL6.U &= ~(0x3 << SEL7_BIT_LSB_IDX);                   // TOUT103 --> TOM0 channel 1
                                                                    // 103 = 16 * 6 + 7
#elif (LAB == 2)
    // set TGC0 to enable GTM TOM0 channel 2, 3, 15
    GTM_TOM0_TGC0_GLB_CTRL.B.UPEN_CTRL2 |= 0x2;                     // TOM0 channel 2 enable
    GTM_TOM0_TGC0_GLB_CTRL.B.UPEN_CTRL3 |= 0x2;                     // TOM0 channel 3 enable
    GTM_TOM0_TGC1_GLB_CTRL.B.UPEN_CTRL7 |= 0x2;                     // TOM0 channel 15 enable

    GTM_TOM0_TGC0_ENDIS_CTRL.B.ENDIS_CTRL2 |= 0x2;                  // enable channel 2 on update trigger
    GTM_TOM0_TGC0_ENDIS_CTRL.B.ENDIS_CTRL3 |= 0x2;                  // enable channel 3 on update trigger
    GTM_TOM0_TGC1_ENDIS_CTRL.B.ENDIS_CTRL7 |= 0x2;                  // enable channel 15 on update trigger

    GTM_TOM0_TGC0_OUTEN_CTRL.B.OUTEN_CTRL2 |= 0x2;                  // enable channel 2 output on update trigger
    GTM_TOM0_TGC0_OUTEN_CTRL.B.OUTEN_CTRL3 |= 0x2;                  // enable channel 3 output on update trigger
    GTM_TOM0_TGC1_OUTEN_CTRL.B.OUTEN_CTRL7 |= 0x2;                  // enable channel 15 output on update trigger

    // TOM 0_2
    GTM_TOM0_CH2_CTRL.U |= 0x1 << SL_BIT_LSB_IDX;

    GTM_TOM0_CH2_CTRL.U &= ~(0x7 << CLK_SRC_SR_BIT_LSB_IDX);
    GTM_TOM0_CH2_CTRL.U |= 0x1 << CLK_SRC_SR_BIT_LSB_IDX;

    GTM_TOM0_CH2_SR0.U = 12500 - 1;

    // TOM 0_3
    GTM_TOM0_CH3_CTRL.U |= 0x1 << SL_BIT_LSB_IDX;

    GTM_TOM0_CH3_CTRL.U &= ~(0x7 << CLK_SRC_SR_BIT_LSB_IDX);
    GTM_TOM0_CH3_CTRL.U |= 0x1 << CLK_SRC_SR_BIT_LSB_IDX;

    GTM_TOM0_CH3_SR0.U = 12500 - 1;

    // TOM 0_15
    GTM_TOM0_CH15_CTRL.B.SL |= 0x1;                                 // high signal level
    GTM_TOM0_CH15_CTRL.B.CLK_SRC_SR |= 0x1;                         // clock source
    GTM_TOM0_CH15_SR0.U = 12500 - 1;


    // TOUT pin selection
    GTM_TOUTSEL6.U &= ~(0x3 << SEL7_BIT_LSB_IDX);
    GTM_TOUTSEL0.U &= ~(0x3 << SEL7_BIT_LSB_IDX);
    GTM_TOUTSEL6.U &= ~(0x3 << SEL11_BIT_LSB_IDX);
    GTM_TOUTSEL0.U &= ~(0x3 << SEL9_BIT_LSB_IDX);

#else
#endif
}

void initRGBLED(void)
{
    // reset Port IOCR register
    P02_IOCR4.U &= ~(0x1F << PC7_BIT_LSB_IDX);          // Port 2 Pin 7
    P10_IOCR4.U &= ~(0x1F << PC5_BIT_LSB_IDX);          // Port 10 Pin 5
    P10_IOCR0.U &= ~(0x1F << PC3_BIT_LSB_IDX);          // Port 10 Pin 3

    // set Port as general purpose output (push-pull)
    P02_IOCR4.U |= (0x10 << PC7_BIT_LSB_IDX);
    P10_IOCR4.U |= (0x10 << PC5_BIT_LSB_IDX);
    P10_IOCR0.U |= (0x10 << PC3_BIT_LSB_IDX);
}

void initVADC(void)
{
    clearLock();

    VADC_CLC.U &= ~(1 << DISR_BIT_LSB_IDX);                 // enable VADC

    setLock();

    //VADC configurations
    while ((VADC_CLC.U & (1 << DISS_BIT_LSB_IDX)) != 0);    // wait until VADC module enabled

    VADC_G4_ARBPR.U |= 0x3 << PRIO0_BIT_LSB_IDX;            // highest priority for Request Source 0
    VADC_G4_ARBPR.U &= ~(0x1 << CSM0_BIT_LSB_IDX);          // Wait-for-Start Mode
    VADC_G4_ARBPR.U |= 0x1 << ASEN0_BIT_LSB_IDX;            // Arbitration Source Input 0 Enable

    VADC_G4_QMR0.U &= ~(0x3 << ENGT_BIT_LSB_IDX);           // gating mode 안쓰겠다
    VADC_G4_QMR0.U |= (0x1 << ENGT_BIT_LSB_IDX);            // enable conversion request
    VADC_G4_QMR0.U |= (0x1 << FLUSH_BIT_LSB_IDX);           // clear ADC queue

    VADC_G4_ARBCFG.U |= (0x3 << ANONC_BIT_LSB_IDX);         // ADC normal operation

    VADC_G4_ICLASS0.U &= ~(0x7 << CMS_BIT_LSB_IDX);         // Class 0 standard Conversion (12-bit)

    // VADC Group 4 Channel 7 configuration
    VADC_G4_CHCTR7.U |= (0x1 << RESPOS_BIT_LSB_IDX);        // result right-algined
    VADC_G4_CHCTR7.U &= ~(0xF << RESREG_BIT_LSB_IDX);       // store result @ Result Register G4RES0
    VADC_G4_CHCTR7.U &= ~(0x3 << ICLSEL_BIT_LSB_IDX);       // Class 0

    VADC_G4_CHASS.U |= (0x1 << ASSCH7_BIT_LSB_IDX);
}

void initERU(void)
{
   // ERU setting
    SCU_EICR1.U &= ~(0x7 << EXIS0_BIT_LSB_IDX); // 000으로 설정
    SCU_EICR1.U |= (0x1 << EXIS0_BIT_LSB_IDX);  // 001설정


    SCU_EICR1.U |= (0x1 << FEN0_BIT_LSB_IDX);   // falling edge
    SCU_EICR1.U |= (0x1 << REN0_BIT_LSB_IDX);   // rising edge


    SCU_EICR1.U |= (0x1 << EIEN0_BIT_LSB_IDX);  // external interrupt interrupt

    SCU_EICR1.U &= ~(0x7 << INP0_BIT_LSB_IDX);  // OGU output channel

    SCU_IGCR0.U &= ~(0x3 << IGP0_BIT_LSB_IDX);
    SCU_IGCR0.U |= (0x1 << IGP0_BIT_LSB_IDX);   // output trigger event to IOUT port in ERU

    //SRC Interrupt setting
    SRC_SCU_SCU_ERU0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_SCU_SCU_ERU0.U |= (0x0A << SRPN_BIT_LSB_IDX);

    SRC_SCU_SCU_ERU0.U &= ~(0x3 << TOS_BIT_LSB_IDX);

    SRC_SCU_SCU_ERU0.U |= (1 << SRE_BIT_LSB_IDX);
}

void initCC60(void)
{
    clearLock();

    CCU60_CLC.U &= ~(1 << DISR_BIT_LSB_IDX);                    // enable CCY

    setLock();

    // CCU60 T12 configurations
    while ((CCU60_CLC.U & (1 << DISS_BIT_LSB_IDX)) != 0);       // wait until CCU60 module enabled

    CCU60_TCTR0.U &= ~(0x7 << T12CLK_BIT_LSB_IDX);              // f_T12 = f_CCU6 / prescaler
    CCU60_TCTR0.U |= 0x2 << T12CLK_BIT_LSB_IDX;                 // f_CCU6 = 50 MHz, prescaler = 1024
    CCU60_TCTR0.U |= 0x1 << T12PRE_BIT_LSB_IDX;                 // f_T12 = 48,828 Hz
    CCU60_TCTR0.U &= ~(0x1 << CTM_BIT_LSB_IDX);              // T12 auto reset when period match (PM) occur

    CCU60_T12PR.U = 24414 - 1;                                  // PM interrupt freq. = f_T12 / (T12PR + 1)
    CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;                 // load T12PR from shadow reg.

    CCU60_T12.U = 0;                                            // clear T12 counter reg.


    // CCU60_T12_PM interrupt setting
    CCU60_INP.U &= ~(0x3 << INPT12_BIT_LSB_IDX);                // service request output SR0 selected
    CCU60_IEN.U |= 0x1 << ENT12PM_BIT_LSB_IDX;                  // enable T12 PM interrupt


    //SRC Interrupt setting
    SRC_CCU6_CCU60_SR0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_CCU6_CCU60_SR0.U |= (0x0B << SRPN_BIT_LSB_IDX);         // set priority 0x0B

    SRC_CCU6_CCU60_SR0.U &= ~(0x3 << TOS_BIT_LSB_IDX);          // CPU0 service T12 PM interrupt

    SRC_CCU6_CCU60_SR0.U |= (0x1 << SRE_BIT_LSB_IDX);           // SR0 enabled

    //CCU60 T12 counting start
    CCU60_TCTR4.U = 0x1 << T12RS_BIT_LSB_IDX;                   // T12 start counting
}

void initLED(void)
{
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);  // reset P10_IOCR0 PC1
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX);  // reset P10_IOCR0 PC1

    P10_IOCR0.U |= 0x10 << PC1_BIT_LSB_IDX;     // set P10.1 push-pull general output
    P10_IOCR0.U |= 0x10 << PC2_BIT_LSB_IDX;     // set P10.1 push-pull general output
}

void initPWMLED(void)
{
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);  // reset P10_IOCR0 PC1
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX);  // reset P10_IOCR0 PC1

    P10_IOCR0.U |= 0x11 << PC1_BIT_LSB_IDX;     // set P10.1 GTM output (PWM)
    P10_IOCR0.U |= 0x10 << PC2_BIT_LSB_IDX;     // set P10.1 push-pull general output
}

void initButton(void){
    P02_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);  // reset P02_IOCR0 PC1
    P02_IOCR0.U |= 0x02 << PC1_BIT_LSB_IDX;     // set P02.1 general input (pull-up connected)

    //P02_IOCR0.B.PC0 = 0x02;
    //P02_IOCR0.B.PC1 = 0x02;
}

__interrupt(0x0A) __vector_table(0)
void ERU0_ISR(void)
{
    // button status check
    if ((P02_IN.U & (0x1 << P1_BIT_LSB_IDX)) == 0)      // button pushed
    {
        P10_OUT.B.P1 = 0x1;
        CCU60_T12PR.U = 12207 - 1;                      // PM interrupt freq. = f_T12 / (T12PR + 1)
        CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;     // load T12PR from shadow register
    }
    else                                                // button released
    {
        P10_OUT.B.P1 = 0x0;
        CCU60_T12PR.U = 24414 - 1;                      // PM interrupt freq. = f_T12 / (T12PR + 1)
        CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;     // load T12PR from shadow register
    }
}

__interrupt(0x0B) __vector_table(0)
// 코드가 실행되는 속도가 interrupt가 돌아오는 속도보다 느리면 overrun이 발생함 => led가 깜빡이는 속도가 달라질 수도 있음
void CCU60_T12_ISR(void)
{
    P10_OUT.U ^= 0x1 << P2_BIT_LSB_IDX;                 // toggle P10.2 (LED D13 BLUE)
}
int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    //initERU();
    initCC60();
    //initLED();
    initPWMLED();
    initRGBLED();
    initVADC();
    initGTM();
    //initButton();

    //int start;

    //unsigned int adcResult;

    // 최초 한번은 복사해야 된다고? 나머지는 AUTOMATIC UPDATE
    GTM_TOM0_TGC0_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX;   // trigger update request signal

#if (LAB == 1)

    while(1)
    {
        unsigned int adcResult;

        VADC_startConversion();
        adcResult = VADC_readResult();

        if (adcResult >= 3096){
            P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;             // 1로 설정
            P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 0;
        }

        else if (adcResult >= 2048)
        {
            P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
            P10_OUT.U |= (0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 1000;
        }

        else if (adcResult >= 1024)
        {
            P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U |= (0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 7000;
        }

        else
        {
            P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
            P10_OUT.U |= (0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U |= (0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 12500;
        }
    }

#elif (LAB == 2)

    GTM_TOM0_TGC1_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX;   // trigger update request signal

    unsigned short duty = 0;

    while (1)
    {
        VADC_startConversion();
        unsigned int adcResult = VADC_readResult();

        duty = 12500 * adcResult / 4096;

        GTM_TOM0_CH2_SR1.U = duty;
        GTM_TOM0_CH3_SR1.U = duty;
        GTM_TOM0_CH15_SR1.U = duty;
    }
#else
#endif
    return (1);
}
