/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IFxCcu6_reg.h"

// Port registers
#define PC1_BIT_LSB_IDX         11
#define PC2_BIT_LSB_IDX         19
#define P1_BIT_LSB_IDX          1
#define P2_BIT_LSB_IDX          2

// SCU REGISTER
#define LCK_BIT_LSB_IDX         1
#define ENDINIT_BIT_LSB_IDX     0
#define EXIS0_BIT_LSB_IDX       4
#define FEN0_BIT_LSB_IDX        8
#define REN0_BIT_LSB_IDX        9
#define EIEN0_BIT_LSB_IDX       11
#define INP0_BIT_LSB_IDX        12
#define IGP0_BIT_LSB_IDX        14

// SRC REGISTERS
#define SRPN_BIT_LSB_IDX        0
#define TOS_BIT_LSB_IDX         11
#define SRE_BIT_LSB_IDX         10

// CCU60 REGISTERS
#define DISS_BIT_LSB_IDX        1
#define DISR_BIT_LSB_IDX        0
#define CTM_BIT_LSB_IDX         7
#define T12PRE_BIT_LSB_IDX      3
#define T12CLK_BIT_LSB_IDX      0
#define T12STR_BIT_LSB_IDX      6
#define T12RS_BIT_LSB_IDX       1
#define INPT12_BIT_LSB_IDX      10
#define ENT12PM_BIT_LSB_IDX     7

IfxCpu_syncEvent g_cpuSyncEvent = 0;

void initCCU60(void);
void initERU(void);
void initLED(void);
void initButton(void);


__interrupt(0x0A)   __vector_table(0) // interrupt 발생 시 호출되는 함수 설정
void ERU0_ISR(void);

__interrupt(0x0B)   __vector_table(0) // interrupt 발생 시 호출되는 함수 설정
void CCU60_T12_ISR(void);


int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    initERU();
    initCCU60();
    initLED();
    initButton();

    // unsigned char pre = 1, cur = 1;

    while(1)
    {
        /*
        // 1. GPIO OUT
        for(uint32 i = 0; i <1000000; i++);   // sw DELAY

        P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX;

        for(uint32 i = 0; i <10000000; i++);   // sw DELAY
        P10_OUT.U ^= 0x1 << P2_BIT_LSB_IDX;

        // 2. GPOI IN
        if( (P02_IN.U & (0x1 << P1_BIT_LSB_IDX)) == 0 ) // check button status
        {
            P10_OUT.U |= 0x1 << P1_BIT_LSB_IDX;         // clear P10.1 (LED D13 RED)
        }
        else
        {
            P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX);      // clear P10.1 (LED D13 RED)
        }
        */

        /*
        // 3.sampling
        int a, b, c;

        // 1 == on
        a = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
        for(uint32 i = 0; i <10000; i++);   // sw DELAY;

        b = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
        for(uint32 i = 0; i <10000; i++);   // sw DELAY

        c = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
        for(uint32 i = 0; i <10000; i++);   // sw DELAY

        if (a == 0 && b == 0 && c == 0){
            P10_OUT.U |= 0x1 << P1_BIT_LSB_IDX;
        }
        else{
            P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX);
        }
        */

        // 4. Edge Detection
        /*
        pre = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
        for(uint32 i = 0; i <10000; i++);   // sw DELAY
        cur = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);

        if ((pre ^ cur) == 1)
        {
            P10_OUT.U |= 0x1 << P1_BIT_LSB_IDX;
            for(uint32 i = 0; i <100000; i++);   // sw DELAY
            P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX);
        }
        */

        // 5. SCU [ERU]

    }


    return (1);
}

void initButton(void)
{
    P02_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);

    P02_IOCR0.U |= 0x02 << PC1_BIT_LSB_IDX;
}

void initLED(void)
{
    // RESET P10_IOCR0 PC1,2
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX);

    // SET P10.1,2 push-pull general output
    P10_IOCR0.U |= (0x10 << PC1_BIT_LSB_IDX);
    P10_IOCR0.U |= (0x10 << PC2_BIT_LSB_IDX);
}


// ERU Interrupt 사용위한 설정
void initERU(void)
{
    // ERU setting
    // ~여기는 초기화
    SCU_EICR1.U &= ~(0x7 << EXIS0_BIT_LSB_IDX);     // EICR1 레지스터에서 사용할 곳[EXIS0] 설정 (1번째 영역)
    SCU_EICR1.U |=  (0x1 << EXIS0_BIT_LSB_IDX);

    // ETL setting
    SCU_EICR1.U |=  0x1 << FEN0_BIT_LSB_IDX;      // Push 버튼의 falling edge 활성화

    // 2 - 버튼 눌렀다 땔 때 반응하도록
    SCU_EICR1.U |=  0x1 << REN0_BIT_LSB_IDX;

    SCU_EICR1.U |=  0x1 << EIEN0_BIT_LSB_IDX;     // trigger enable 만들기

    // OGU - Output Gating Unit - Trigger 이벤트 조합하여 Request 출력 만드는 곳
    SCU_EICR1.U &= ~(0x7 << INP0_BIT_LSB_IDX);

    // IGCR - 입력되는 트리거 신호 연결
    SCU_IGCR0.U &= ~(0x3 << IGP0_BIT_LSB_IDX);
    SCU_IGCR0.U |=  (0x1 << IGP0_BIT_LSB_IDX);

    // SRC Interrupt setting
    SRC_SCU_SCU_ERU0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_SCU_SCU_ERU0.U |=   0x0A << SRPN_BIT_LSB_IDX;       // 우선순위 및 고유 인식 설정

    SRC_SCU_SCU_ERU0.U &= ~(0x3  << TOS_BIT_LSB_IDX);       //  TOS 설정  - CPU0

    SRC_SCU_SCU_ERU0.U |=   1    << SRE_BIT_LSB_IDX;        // SRE 1로 설정 - interrupt enable
}

void ERU0_ISR(void)
{
    // 0
    /*
    P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX; // 눌렸을 경우 반짝이게 ==>
    */

    // 1
    /*
    P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX;
    for(uint32 i = 0; i <300000; i++);   // sw DELAY;
    P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX); // 눌렸을 경우 반짝이게
    */

    // 2는 init-setting ㄱㄱ

    // 3
    /*
    unsigned char a,b,c;

    a = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(uint32 i = 0; i <10000000; i++);   // sw DELAY;

    b = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(uint32 i = 0; i <10000000; i++);   // sw DELAY;

    c = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(uint32 i = 0; i <10000000; i++);   // sw DELAY;

    if ( a == 0 && b == 0 && c == 0)
    {
        P10_OUT.U |= 0x1 << P1_BIT_LSB_IDX;
        for(uint32 i = 0; i <5000000; i++);   // sw DELAY;
        P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX); // 눌렸을 경우 반짝이게
    }
    */

    // 보충 lab

    if((P02_IN.U & (0x1 << P1_BIT_LSB_IDX)) == 0)   // BUTTON PUSHED
    {
        P10_OUT.B.P1 = 0x1;
        CCU60_T12PR.U = 12207 - 1;
        CCU60_TCTR4.U = 0x1 << T12STR_BIT_LSB_IDX;  // shadow register로 보내기
    }
    else    // Button released
    {
        P10_OUT.B.P1 = 0x0;
        CCU60_T12PR.U = 24414 - 1;
        CCU60_TCTR4.U = 0x1 << T12STR_BIT_LSB_IDX;
    }
}

void CCU60_T12_ISR(void){
    P10_OUT.U ^= 0x1 << P2_BIT_LSB_IDX; // 푸른 색 토글
}


void initCCU60(void)
// unlock => ENDINIT clear => CCY Enable => SCU_WDTSCON0 unlock => ENDINIT set
// [최종 목표]CLC를 Enable로 하기 위해서 ENDINIT이 0이어야함 => ENDINIT을 풀기위해서는 LCK를 풀어야함
// => LCK를 풀기 위해 PW Access 해야함 => LCK 해제 - ENDINIT 값 바꿈 -> 바로 잠금
{
    // PW Access to unlock SCU_WDTSCON0
            // ^를 통해 원래대로 바꿈 -> PW는 반전되어 받으므로
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);  // unlock 대기

    // Modify Access to clear ENDINIT => Mask 작업
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) & ~(1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);  // lock 대기

    // Enable CCY [CLC 변경]
    CCU60_CLC.U &= ~(1 << DISR_BIT_LSB_IDX);

    // Password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);  // unlock 대기

    // Modify Access to set ENDINIT => 0으로 set해주어 보호 레지스터 CLC에 값 사용 가능
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);  // lock 대기

        // ------- 위는 CLC - ENDINIT - LCK - PW - LCK - ENDINIT - CLC사용

    // CCU60 T12 configurations [DISS - 0 / DISR - 0 => Clock enable]
    while((CCU60_CLC.U & (1 << DISS_BIT_LSB_IDX)) != 0); // wait until CCU60 module enabled

    // 내부 clock 주파수 설정
    CCU60_TCTR0.U &= ~(0x7 << T12CLK_BIT_LSB_IDX);    // f_T12 = f_CCU6 / prescaler
    CCU60_TCTR0.U |= 0x2 << T12CLK_BIT_LSB_IDX;       // f_CCU6 = 50MHz, prescaler = 1024
    CCU60_TCTR0.U |= 0x1 << T12PRE_BIT_LSB_IDX;       // f_T12 = 48,828 Hz

    // T12 모듈에서 자동으로 초기화 시켜주기 위해 CTM 변경
    CCU60_TCTR0.U &= ~(0x1 << CTM_BIT_LSB_IDX);       // T12 auto reset when period match occur
        // --- 위는 T12 모듈 설정

    // 주기 T12PR 설정 [ 24414 - 1 => 48828 / 2 - 1==> 0.5s ]
    CCU60_T12PR.U = 24414 -1;                           // PM interrupt freq. = f_T12 / (T12PR + 1)

    // T12PR -> Write 값은 Period Shadow Register 머무름 -> T12STR이 1이 되면 Shadow Enable
    CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;         // Load T12PR from shadow regist

    // T1 counter 값 초기화 인데 이유는? => 후에 counter 증가 동작이므로 초기화 후 증가 필요
    CCU60_T12.U = 0;        // clear T12 counter regist

            // 타이머 인터럽트 발생 설정
        // CCU60_T12 PM interrupt setting
    // T12에서 발생한 INTERRUPT를 IR로 전달하기 위해 INPT12 영역 0
    CCU60_INP.U &= ~(0x3 << INPT12_BIT_LSB_IDX);
    // T12 모듈에서 Period Match 마다 enable하기 위해 ENT12PM 1로
    CCU60_IEN.U |= 0x1 << ENT12PM_BIT_LSB_IDX;


    // SRC setting for CCU60 - T12에서 발생한 INTERRUPT를 SR0에만 연결하기 위한 설정 (원래는 4개)
    SRC_CCU6_CCU60_SR0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_CCU6_CCU60_SR0.U |= (0x0B << SRPN_BIT_LSB_IDX);

    // TOS - CPU0에서 처리 설정 => 0
    SRC_CCU6_CCU60_SR0.U &= ~(0x3 << TOS_BIT_LSB_IDX);

    // SRE - Interrupt를 enable로 설정 => 0
    SRC_CCU6_CCU60_SR0.U |= (0x1 << SRE_BIT_LSB_IDX);

    // CCU60 T12 COUNTING START
    CCU60_TCTR4.U = 0x1 << T12RS_BIT_LSB_IDX;
}
