/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxCcu6_reg.h"
#include "IfxVadc_reg.h"
#include "IfxGtm_reg.h"

//Port registers

#define SRPN_BIT_LSB_IDX 0
#define TOS_BIT_LSB_IDX 11
#define SRE_BIT_LSB_IDX 10
#define PC1_BIT_LSB_IDX 11
#define PC2_BIT_LSB_IDX 19
#define P1_BIT_LSB_IDX  1
#define P2_BIT_LSB_IDX  2
#define PC7_BIT_LSB_IDX 27
#define PC5_BIT_LSB_IDX 11
#define PC3_BIT_LSB_IDX 27
#define P7_BIT_LSB_IDX 7
#define P5_BIT_LSB_IDX 5
#define P3_BIT_LSB_IDX 3


//SCU register
#define EXIS0_BIT_LSB_IDX 4
#define FEN0_BIT_LSB_IDX 8
#define EIEN0_BIT_LSB_IDX 11
#define INP0_BIT_LSB_IDX 12
#define IGP0_BIT_LSB_IDX 14
#define REN0_BIT_LSB_IDX 9

#define LCK_BIT_LSB_IDX 1
#define ENDINIT_BIT_LSB_IDX 0

//CCU60 registers
#define DISS_BIT_LSB_IDX 1
#define DISR_BIT_LSB_IDX 0
#define CTM_BIT_LSB_IDX 7
#define T12PRE_BIT_LSB_IDX 3
#define T12CLK_BIT_LSB_IDX 0
#define T12STR_BIT_LSB_IDX 6
#define T12RS_BIT_LSB_IDX 1
#define INPT12_BIT_LSB_IDX 10
#define ENT12PM_BIT_LSB_IDX 7

//VADC Registers
#define ANONC_BIT_LSB_IDX 0
#define PRIO0_BIT_LSB_IDX 0
#define ASEN0_BIT_LSB_IDX 24
#define CSM0_BIT_LSB_IDX 3
#define CMS_BIT_LSB_IDX 8
#define FLUSH_BIT_LSB_IDX 10
#define TREV_BIT_LSB_IDX 9
#define ENGT_BIT_LSB_IDX 0
#define RESPOS_BIT_LSB_IDX 21
#define RESREG_BIT_LSB_IDX 16
#define ICLSEL_BIT_LSB_IDX 0
#define VF_BIT_LSB_IDX 31
#define RESULT_BIT_LSB_IDX 0
#define ASSCH7_BIT_LSB_IDX 7

//GTM registers
#define SEL7_BIT_LSB_IDX 14
#define EN_FXCLK_BIT_LSB_IDX 22
#define FXCLK_SEL_BIT_LSB_IDX 0

//GTM-TOM0 Registers
#define UPEN_CTRL1_BIT_LSB_IDX 18
#define HOST_TRIG_BIT_LSB_IDX 0
#define ENDIS_CTRL1_BIT_LSB_IDX 2
#define OUTEN_CTRL1_BIT_LSB_IDX 2
#define CLK_SRC_SR_BIT_LSB_IDX 12
#define OSM_BIT_LSB_IDX 26
#define TRIGOUT_BIT_LSB_IDX 24
#define SL_BIT_LSB_IDX 11






IfxCpu_syncEvent g_cpuSyncEvent = 0;




void initRGBLED(void)
{
    //reset Port IOCR register
    P02_IOCR4.U &= ~(0x1F << PC7_BIT_LSB_IDX); //ledR을 Outputpushpull로 사용하기 전에 일단 리셋시킨다.
    P10_IOCR4.U &= ~(0x1F << PC5_BIT_LSB_IDX);
    P10_IOCR0.U &= ~(0x1F << PC3_BIT_LSB_IDX);

    //set Port as general purpose output(push-pull)
    P02_IOCR4.U |= 0x10 << PC7_BIT_LSB_IDX; //P02.7 //그담에 그 출력모드로 해야되니까 표 보고 10000을 적는다.
    P10_IOCR4.U |= 0x10 << PC5_BIT_LSB_IDX; //P10.5
    P10_IOCR0.U |= 0x10 << PC3_BIT_LSB_IDX; //P10.3
}

void initLED(void)
{
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX);

    P10_IOCR0.U |= 0x10 << PC1_BIT_LSB_IDX; //얜 그냥 led (push pull)
    P10_IOCR0.U |= 0x10 << PC2_BIT_LSB_IDX;
}

void initPWMLED(void)
{
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX);

    P10_IOCR0.U |= 0x11 << PC1_BIT_LSB_IDX; //set 10.1 GTM Output 얜 pwmled
    P10_IOCR0.U |= 0x10 << PC2_BIT_LSB_IDX;
}

void VADC_startConversion(void)
{
    VADC_G4_QINR0.U |= 0x07;    //no. of request channel = 7

    VADC_G4_QMR0.U |= 0x1 << TREV_BIT_LSB_IDX; //generate conversion start trigger event
}

/*
void initButton(void)
{
    P02_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);

    P02_IOCR0.U |= 0x02 << PC1_BIT_LSB_IDX;
}
*/

void initERU(void)
{
 //ERD Setting
    SCU_EICR1.U &= ~(0x7 << EXIS0_BIT_LSB_IDX); //스위치 3번핀을 인터럽트로 쓰겠다.
    SCU_EICR1.U |= (0x1 << EXIS0_BIT_LSB_IDX);

   // SCU_EICR1.U |= 0x1 << FEN0_BIT_LSB_IDX;

    SCU_EICR1.U |= 0x1 << REN0_BIT_LSB_IDX; //rising edge


    SCU_EICR1.U |= 0x1 << EIEN0_BIT_LSB_IDX;

    SCU_EICR1.U &= ~(0x7 << INP0_BIT_LSB_IDX);

    SCU_IGCR0.U &= ~(0x3 << IGP0_BIT_LSB_IDX);
    SCU_IGCR0.U |= 0x1 << IGP0_BIT_LSB_IDX;

    //SRC Interrupt setting
    SRC_SCU_SCU_ERU0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_SCU_SCU_ERU0.U |= 0x0A << SRPN_BIT_LSB_IDX;

    SRC_SCU_SCU_ERU0.U &= ~(0x3 << TOS_BIT_LSB_IDX);

    SRC_SCU_SCU_ERU0.U |= 1 << SRE_BIT_LSB_IDX;
}



void initCCU60(void)
{
    //Password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC)&~(1<< LCK_BIT_LSB_IDX)) | (1<< ENDINIT_BIT_LSB_IDX);
    //LCK를 0으로 풀어야 ENDINIT을 0으로 바꿀 수 있음. 일단은 LCK를 0으로 푼다. SCU~여기는 반전해가지고 1을 반전해야하니까 최종적으론 다 0이 되게.
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX))!=0);
    //다시한번 확인해주는 거야. LCK이 0이 됐는지. LCK는 0이될때까지 시간이 좀 걸려서 ..

    //Modify Access to clear ENDINIT
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC)|(1<< LCK_BIT_LSB_IDX)) & ~(1<< ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX))==0);
    //락이 셋팅됐는지 확인

    CCU60_CLC.U &= ~(1 << DISR_BIT_LSB_IDX); //Clear. DISR에 0을 쓰면  ENable됨.

    //password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U  = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1<<LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);

    //Modify access to set ENDINIT
        SCU_WDTCPU0_CON0.U  = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1<<LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
        while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

    //CCU60 T12 configurations
    while((CCU60_CLC.U & (1 << DISS_BIT_LSB_IDX)) !=0); //wait until CCU60 module enabled

    CCU60_TCTR0.U &= ~(0x7 << T12CLK_BIT_LSB_IDX); //f_T12=f_CCU6 / prescaler
    CCU60_TCTR0.U |= 0x2 << T12CLK_BIT_LSB_IDX;
    CCU60_TCTR0.U |= 0x1 << T12PRE_BIT_LSB_IDX;

    CCU60_TCTR0.U &= ~(0x1 << CTM_BIT_LSB_IDX);

    CCU60_T12PR.U = 12207-1; // PM interrupt freq. 공식은 외우지말자. 0.5초로 되는 것. 48828/2 -1임. 나누기2하니까 0.5초로 .
    CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX; //load T12PR from shadow register// 1bit니까 굳이 clear할 필요없이 그냥 1쓰면됨.

    CCU60_T12.U = 0; //clear T12 Counter register

    CCU60_INP.U &= ~(0x3 << INPT12_BIT_LSB_IDX);
    CCU60_IEN.U |= 0x1 << ENT12PM_BIT_LSB_IDX;

    SRC_CCU6_CCU60_SR0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_CCU6_CCU60_SR0.U |= (0x0B << SRPN_BIT_LSB_IDX); //set priority 0x0B

    SRC_CCU6_CCU60_SR0.U &= ~(0x3 << TOS_BIT_LSB_IDX); //CPU0 service T12 PM interrupt

    SRC_CCU6_CCU60_SR0.U |= (0x1 << SRE_BIT_LSB_IDX); //SR0 enabled


    CCU60_TCTR4.U = 0x1 << T12RS_BIT_LSB_IDX; //T12 start counting //이제 최종적으로  run 을 시작시켜주겠다.
}


/*
__interrupt(0x0A)__vector_table(0)
void ERU0_ISR(void)
{

    P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX; //toggle P10.1 (LED D12 RED)
    for (unsigned int i=0; i<300000; i++);
    P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX);

    unsigned char a, b, c;

    a= P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(unsigned int i=0; i<1000000; i++);

    b= P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(unsigned int i=0; i<1000000; i++);

    c= P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(unsigned int i=0; i<1000000; i++);

    if( (a==0) && (b==0) && (c==0))
    {
        P10_OUT.U |= (0x1 << P1_BIT_LSB_IDX);
        for(unsigned int i=0; i<500000; i++);
        P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX);
    }
}
*/

void initVADC(void)
{
    //Password Access to unlock SCU_WDTSCON0
        SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC)&~(1<< LCK_BIT_LSB_IDX)) | (1<< ENDINIT_BIT_LSB_IDX);
        //LCK를 0으로 풀어야 ENDINIT을 0으로 바꿀 수 있음. 일단은 LCK를 0으로 푼다. SCU~여기는 반전해가지고 1을 반전해야하니까 최종적으론 다 0이 되게.
        while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX))!=0);
        //다시한번 확인해주는 거야. LCK이 0이 됐는지. LCK는 0이될때까지 시간이 좀 걸려서 ..

        //Modify Access to clear ENDINIT
        SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC)|(1<< LCK_BIT_LSB_IDX)) & ~(1<< ENDINIT_BIT_LSB_IDX);
        while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX))==0);
        //락이 셋팅됐는지 확인

        VADC_CLC.U &= ~(1 << DISR_BIT_LSB_IDX); //Clear. DISR에 0을 쓰면  ENable됨.

        //password Access to unlock SCU_WDTSCON0
        SCU_WDTCPU0_CON0.U  = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1<<LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
        while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);

        //Modify access to set ENDINIT
        SCU_WDTCPU0_CON0.U  = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1<<LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
        while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

        //VADC configurations
        while((VADC_CLC.U & (1 << DISS_BIT_LSB_IDX)) != 0); //wait until VADC module enabled



        VADC_G4_ARBPR.U |= 0x3 << PRIO0_BIT_LSB_IDX; //highest priority for request source
        VADC_G4_ARBPR.U &= ~(0x1 << CSM0_BIT_LSB_IDX); //wait-for-start mode
        VADC_G4_ARBPR.U |= 0x1 << ASEN0_BIT_LSB_IDX; //arbitration source input 0 enable

        VADC_G4_QMR0.U &= ~(0x3 << ENGT_BIT_LSB_IDX);
        VADC_G4_QMR0.U |= (0x1 << ENGT_BIT_LSB_IDX); //enable conversion request//게이팅모드 쓰지 않음
        VADC_G4_QMR0.U |= (0x1 << FLUSH_BIT_LSB_IDX); //Clear ADC queue

        VADC_G4_ARBCFG.U |= 0x3 << ANONC_BIT_LSB_IDX; //ADC normal operation

        VADC_G4_ICLASS0.U &= ~(07 << CMS_BIT_LSB_IDX); //Class 0 Standard Conversion (12bit)
           //12BIT를 모두 쓰겠다. 모드 클리어해서.

        //VADC Group 4 channel 7 configuration
        VADC_G4_CHCTR7.U |= 0x1 << RESPOS_BIT_LSB_IDX; //result right-alligned
        VADC_G4_CHCTR7.U &= ~(0xF << RESREG_BIT_LSB_IDX); //store result @ Result register G4RES0
        VADC_G4_CHCTR7.U &= ~(0X3 << ICLSEL_BIT_LSB_IDX);

        VADC_G4_CHASS.U |= 0X1 << ASSCH7_BIT_LSB_IDX;

}

void initGTM(void)
{
    //Password Access to unlock SCU_WDTSCON0
        SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC)&~(1<< LCK_BIT_LSB_IDX)) | (1<< ENDINIT_BIT_LSB_IDX);
        //LCK를 0으로 풀어야 ENDINIT을 0으로 바꿀 수 있음. 일단은 LCK를 0으로 푼다. SCU~여기는 반전해가지고 1을 반전해야하니까 최종적으론 다 0이 되게.
        while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX))!=0);
        //다시한번 확인해주는 거야. LCK이 0이 됐는지. LCK는 0이될때까지 시간이 좀 걸려서 ..

        //Modify Access to clear ENDINIT
        SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC)|(1<< LCK_BIT_LSB_IDX)) & ~(1<< ENDINIT_BIT_LSB_IDX);
        while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX))==0);
        //락이 셋팅됐는지 확인

        GTM_CLC.U &= ~(1 << DISR_BIT_LSB_IDX); //Clear. DISR에 0을 쓰면  ENable됨.

        //password Access to unlock SCU_WDTSCON0
        SCU_WDTCPU0_CON0.U  = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1<<LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
        while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);

        //Modify access to set ENDINIT
        SCU_WDTCPU0_CON0.U  = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1<<LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
        while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

        while((GTM_CLC.U & (1<< DISS_BIT_LSB_IDX)) != 0); //wait until GTM Module enabled

        GTM_CMU_FXCLK_CTRL.U &= ~(0xF << FXCLK_SEL_BIT_LSB_IDX); //input clock of CMU FXCLK -->CMU GCLK_EN
        GTM_CMU_CLK_EN.U |= 0x2 << EN_FXCLK_BIT_LSB_IDX; //enable all CMU_FXCLK

        //GTM TMO0 PWM configuration
        GTM_TOM0_TGC0_GLB_CTRL.U |= 0x2 << UPEN_CTRL1_BIT_LSB_IDX; //채널1을 활성화하는데 쉐도의 01이 CM01로 업데이트를 허용한다.

        GTM_TOM0_TGC0_ENDIS_CTRL.U |= 0x2 << ENDIS_CTRL1_BIT_LSB_IDX; //enable channel 1 on update trigger
//channel1번에서 나가는 신호가 트리거 되게?
        GTM_TOM0_TGC0_OUTEN_CTRL.U |= 0x2 << OUTEN_CTRL1_BIT_LSB_IDX; //enable channel 1 output on update trigger
//
        GTM_TOM0_CH1_CTRL.U |= 0x1 << SL_BIT_LSB_IDX; //high signal level for duty cycle
        GTM_TOM0_CH1_CTRL.U |= 0x1 << CLK_SRC_SR_BIT_LSB_IDX;
        GTM_TOM0_CH1_CTRL.U &= ~(0x1 << OSM_BIT_LSB_IDX);
        GTM_TOM0_CH1_CTRL.U &= ~(0x1 << TRIGOUT_BIT_LSB_IDX);

        GTM_TOM0_CH1_SR0.U = 12500-1;

        GTM_TOM0_CH1_SR1.U = 1250-1;

        GTM_TOUTSEL6.U &= ~(0x3 << SEL7_BIT_LSB_IDX);


        GTM_TOUTSEL6.U &= ~(0x3 << SEL7_BIT_LSB_IDX); //TOUT103 --> TOM0 channel 1
        // 103 = 16*6+7


}

unsigned int VADC_readResult(void)
{
    unsigned int result;

    while((VADC_G4_RES0.U & (0x1 << VF_BIT_LSB_IDX))==0);   //wait until read available
    result = VADC_G4_RES0.U & (0xFFF << RESULT_BIT_LSB_IDX); //read ADC value

    return result;
}

__interrupt(0x0A)__vector_table(0)
void ERU0_ISR(void)
{
    //button status check
    if((P02_IN.U & (0x1 << P1_BIT_LSB_IDX))==0) //button pushed
    {
        P10_OUT.B.P1 = 0x1;
        CCU60_T12PR.U = 12207 -1; // PM interrupt freq=f_T12/(T12PR+1)
        CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX; //load T12PR from shadow register
    }

    else
    {
        P10_OUT.B.P1 = 0x0;
        CCU60_T12PR.U = 24414-1; //PM interrupt freq =f_T12/(T12PR+1)
        CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX; //LOAD t12pr FROM SHADOW REGISTER
    }
}


unsigned int adcResult;

__interrupt(0x0B)__vector_table(0)
void CCU60_T12_ISR(void)
{
   P10_OUT.U ^= 0x1 << P2_BIT_LSB_IDX; //toggle P10.2(LED D13 BLUE)


}


int core0_main(void)
{

    IfxCpu_enableInterrupts();
    /*
     !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
*/
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event*/
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initERU();
    initCCU60();
    //initLED();
    initRGBLED();
    initVADC();
    initGTM();
    initPWMLED();

    //initButton();

    GTM_TOM0_TGC0_GLB_CTRL.U |= 0X1 << HOST_TRIG_BIT_LSB_IDX; //최초한번은 SM에서 CM0로 복사를 한다.
    //trigger update request signal


    while(1)

    {
        VADC_startConversion();
        unsigned int adcResult = VADC_readResult();
        /*
        unsigned int duty;
        duty=12500*adcResult/4096;
        GTM_TOM0_CH1_SR1.U=duty;
        */

        for(unsigned int i=0; i<100; i++);

        if( adcResult >= 3096)
        {
            P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX; //led에 전압1을 가해야 on되는데 on되려면 p7자리에 1이 와야된다.
            P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 0;
        }
        else if (adcResult >= 2048)
        {
            P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
            P10_OUT.U |= (0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 1000;
        }
        else if (adcResult >= 1024)
        {
            P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U |= (0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 7000;
        }
        else
        {
            P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
            P10_OUT.U |= (0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U |= (0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 12500;
        }

    }
/*
    {
        for(unsigned int i =0; i<10000000; i++);
        P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
        P10_OUT.U |= 0x1 << P5_BIT_LSB_IDX;
        P10_OUT.U |= 0x1 << P3_BIT_LSB_IDX;

        for(unsigned int i =0; i<10000000; i++);
        P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
        P10_OUT.U |= 0x1 << P5_BIT_LSB_IDX;
        P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);

        for(unsigned int i =0; i<10000000; i++);
        P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
        P10_OUT.U |= (0x1 << P5_BIT_LSB_IDX);
        P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);

        for(unsigned int i =0; i<10000000; i++);
        P02_OUT.U |= (0x1 << P7_BIT_LSB_IDX);
        P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
        P10_OUT.U |= 0x1 << P3_BIT_LSB_IDX;
    }
    */

    return (1);
}


