/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxCcu6_reg.h"
#include "IfxVadc_reg.h"
#include "IfxGtm_reg.h"

// Port Registers
#define PC1_BIT_LSB_IDX   11
#define PC2_BIT_LSB_IDX   19
#define PC3_BIT_LSB_IDX   27
#define PC5_BIT_LSB_IDX   11
#define PC7_BIT_LSB_IDX   27
#define P1_BIT_LSB_IDX    1
#define P2_BIT_LSB_IDX    2
#define P3_BIT_LSB_IDX    3
#define P5_BIT_LSB_IDX    5
#define P7_BIT_LSB_IDX    7


// SCU Registers
#define LCK_BIT_LSB_IDX   1
#define ENDINIT_BIT_LSB_IDX 0
#define EXIS0_BIT_LSB_IDX 4
#define FEN0_BIT_LSB_IDX  8
#define REN0_BIT_LSB_IDX  9
#define EIEN0_BIT_LSB_IDX 11
#define INP0_BIT_LSB_IDX  12
#define IGP0_BIT_LSB_IDX  14

// SRC Registers
#define SRPN_BIT_LSB_IDX  0
#define TOS_BIT_LSB_IDX   11
#define SRE_BIT_LSB_IDX   10

// CCU60 Registers
#define DISS_BIT_LSB_IDX  1
#define DISR_BIT_LSB_IDX  0
#define CTM_BIT_LSB_IDX   7
#define T12PRE_BIT_LSB_IDX 3
#define T12CLK_BIT_LSB_IDX 0
#define T12STR_BIT_LSB_IDX 6
#define T12RS_BIT_LSB_IDX  1
#define INPT12_BIT_LSB_IDX 10
#define ENT12PM_BIT_LSB_IDX 7

#define SRPN_BIT_LSB_IDX   0
#define TOS_BIT_LSB_IDX    11
#define SRE_BIT_LSB_IDX    10

// VADC Registers
#define ANONC_BIT_LSB_IDX  0
#define ASEN0_BIT_LSB_IDX  24
#define CSM0_BIT_LSB_IDX   3
#define PRIO0_BIT_LSB_IDX  0
#define CMS_BIT_LSB_IDX    8
#define FLUSH_BIT_LSB_IDX  10
#define TREV_BIT_LSB_IDX   9
#define ENGT_BIT_LSB_IDX   0
#define RESPOS_BIT_LSB_IDX 21
#define RESREG_BIT_LSB_IDX 16
#define ICLSEL_BIT_LSB_IDX 0
#define VF_BIT_LSB_IDX     31
#define RESULT_BIT_LSB_IDX 0
#define ASSCH7_BIT_LSB_IDX 7

//GTM Registers
#define SEL7_BIT_LSB_IDX      14
#define SEL9_BIT_LSB_IDX      18
#define SEL11_BIT_LSB_IDX     22
#define EN_FXCLK_BIT_LSB_IDX  22
#define FXCLK_SEL_BIT_LSB_IDX     0

// GTM - TOM0 Registers
#define UPEN_CTRL1_BIT_LSB_IDX  18
#define HOST_TRIG_BIT_LSB_IDX  0
#define ENDIS_CTRL1_BIT_LSB_IDX 2
#define OUTEN_CTRL1_BIT_LSB_IDX 2
#define CLK_SRC_SR_BIT_LSB_IDX  12
#define OSM_BIT_LSB_IDX         26
#define TRIGOUT_BIT_LSB_IDX     24
#define SL_BIT_LSB_IDX          11


void initGTM(void)
{
     // Password Access to unlock SCU_WDTSCON0
     SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
     while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);

     // Modify Access to clear ENDINIT
     SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) & ~(1 << ENDINIT_BIT_LSB_IDX);
     while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

     // Set GTM -> CLC Enable
     GTM_CLC.U &= ~(1 << DISR_BIT_LSB_IDX);

     // Password Access to unlock SCU_WDTSCON0
     SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
     while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);

     // Modify Access to set ENDINIT
     SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
     while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

     while((GTM_CLC.U & (1 << DISS_BIT_LSB_IDX)) != 0);

     //GTM clock configuration
     GTM_CMU_FXCLK_CTRL.U &= ~(0xF << FXCLK_SEL_BIT_LSB_IDX); // input clock of CMU_FXCLK --> CMU_GCLK_EN
     GTM_CMU_CLK_EN.U |= 0x2 << EN_FXCLK_BIT_LSB_IDX; // enable all CMU_FXCLK

     GTM_TOM0_TGC0_GLB_CTRL.U |= 0x2 << UPEN_CTRL1_BIT_LSB_IDX; // Period, Duty update enable

     GTM_TOM0_TGC0_ENDIS_CTRL.U |= 0x2 << ENDIS_CTRL1_BIT_LSB_IDX; // enable channel 1 on update trigger

     GTM_TOM0_TGC0_OUTEN_CTRL.U |= 0x2 << OUTEN_CTRL1_BIT_LSB_IDX; // enable channel 1 output on update trigger

     GTM_TOM0_CH1_CTRL.U |= 0x1 << SL_BIT_LSB_IDX; // Set duty cycle High signal level
     GTM_TOM0_CH1_CTRL.U |= 0x1 << CLK_SRC_SR_BIT_LSB_IDX; // set FXCLK 100MHz/16 = 6250kHx
     GTM_TOM0_CH1_CTRL.U &= ~(0x1 << OSM_BIT_LSB_IDX); // set PWM continuous mode
     GTM_TOM0_CH1_CTRL.U &= ~(0x1 << TRIGOUT_BIT_LSB_IDX); // PWM's first period (CN0 = CM0) trigger -> to next trigger

     // REG LED Dimming
     GTM_TOM0_TGC0_GLB_CTRL.B.UPEN_CTRL2 |= 0x2;
     GTM_TOM0_TGC0_GLB_CTRL.B.UPEN_CTRL3 |= 0x2;
     GTM_TOM0_TGC1_GLB_CTRL.B.UPEN_CTRL7 |= 0x2;

     GTM_TOM0_TGC0_ENDIS_CTRL.B.ENDIS_CTRL2 |= 0x2;
     GTM_TOM0_TGC0_ENDIS_CTRL.B.ENDIS_CTRL3 |= 0x2;
     GTM_TOM0_TGC1_ENDIS_CTRL.B.ENDIS_CTRL7 |= 0x2;

     GTM_TOM0_TGC0_OUTEN_CTRL.B.OUTEN_CTRL2 |= 0x2;
     GTM_TOM0_TGC0_OUTEN_CTRL.B.OUTEN_CTRL3 |= 0x2;
     GTM_TOM0_TGC1_OUTEN_CTRL.B.OUTEN_CTRL7 |= 0x2;

     GTM_TOM0_CH2_CTRL.U |= 0x1 << SL_BIT_LSB_IDX;
     GTM_TOM0_CH1_CTRL.B.CLK_SRC_SR |= 0x1;
     GTM_TOM0_CH2_SR0.U = 12500 - 1;

     GTM_TOM0_CH3_CTRL.U |= 0x1 << SL_BIT_LSB_IDX;
     GTM_TOM0_CH3_CTRL.B.CLK_SRC_SR |= 0x1;
     GTM_TOM0_CH3_SR0.U = 12500 - 1;

     GTM_TOM0_CH15_CTRL.U |= 0x1 << SL_BIT_LSB_IDX;
     GTM_TOM0_CH15_CTRL.B.CLK_SRC_SR |= 0x1;
     GTM_TOM0_CH15_SR0.U = 12500 - 1;

     GTM_TOUTSEL6.U &= ~(0x3 << SEL7_BIT_LSB_IDX);
     GTM_TOUTSEL0.U &= ~(0x3 << SEL7_BIT_LSB_IDX);
     GTM_TOUTSEL6.U &= ~(0x3 << SEL11_BIT_LSB_IDX);
     GTM_TOUTSEL6.U &= ~(0x3 << SEL9_BIT_LSB_IDX);

     GTM_TOM0_CH1_SR0.U = 12500 - 1;  // set PWN frequency 2ms : 12500 / 6250kHz
     GTM_TOM0_CH1_SR0.U = 1250 - 1; // 10% duty cycle

     GTM_TOUTSEL6.U &= ~(0x3 << SEL7_BIT_LSB_IDX); // P10.1 -> TOUT103 -> TOUTSEL6.SEL7 -> choose timer A ( TOM0 -> TOM_CH1)
}

void initRGBLED(void)
{
    // Reset Port_IOCR register
    P02_IOCR4.U &= ~(0x1F << PC7_BIT_LSB_IDX); // P02 -> IOCR4 - > PC7
    P10_IOCR4.U &= ~(0x1F << PC5_BIT_LSB_IDX); // P10 -> IOCR4 -> PC5
    P10_IOCR0.U &= ~(0x1F << PC3_BIT_LSB_IDX); // P10 -> IOCR0 -> PC3

    // Set Port as general purpose output
    P02_IOCR4.U |= 0x11 << PC7_BIT_LSB_IDX;
    P10_IOCR4.U |= 0x11 << PC5_BIT_LSB_IDX;
    P10_IOCR0.U |= 0x11 << PC3_BIT_LSB_IDX;
}

void endRGBLED(void)
{
    P02_IOCR4.U &= ~(0x1F << PC7_BIT_LSB_IDX); // P02 -> IOCR4 - > PC7
    P10_IOCR4.U &= ~(0x1F << PC5_BIT_LSB_IDX); // P10 -> IOCR4 -> PC5
    P10_IOCR0.U &= ~(0x1F << PC3_BIT_LSB_IDX); // P10 -> IOCR0 -> PC3
}

void initPWMLED(void)
{
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX); // reset P10_IOCR0 PC1
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX); // reset P10_IOCR0 PC2
    P10_IOCR0.U |= 0x11 << PC1_BIT_LSB_IDX;    // set P10.1 GTM output (PWN)
    P10_IOCR0.U |= 0x10 << PC2_BIT_LSB_IDX;    // set P10.2 push-pull general output
}


void initLED(void)
{
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX); // reset P10_IOCR0 PC1
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX); // reset P10_IOCR0 PC2
    P10_IOCR0.U |= 0x10 << PC1_BIT_LSB_IDX;    // set P10.1 push-pull general output
    P10_IOCR0.U |= 0x10 << PC2_BIT_LSB_IDX;    // set P10.2 push-pull general output
}

void initButton(void)
{
    P02_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);
    P02_IOCR0.U |= 0x02 << PC1_BIT_LSB_IDX;

}

void initERU(void)
{
    // ERS2 -> EXIS0 -> P02.1 Pin Selection
    SCU_EICR1.U &= ~(0x7 << EXIS0_BIT_LSB_IDX);
    SCU_EICR1.U |= 0x1 << EXIS0_BIT_LSB_IDX;

    // ETL -> EXIS0 -> Falling Edge & Trigger Enable
    //SCU_EICR1.U |= 0x1 << FEN0_BIT_LSB_IDX;
    SCU_EICR1.U |= 0x1 << REN0_BIT_LSB_IDX;

    SCU_EICR1.U |= 0x1 << EIEN0_BIT_LSB_IDX;

    // ERS2 -> INP0 -> OCU0 Setting
    SCU_EICR1.U &= ~(0x7 << INP0_BIT_LSB_IDX);

    // OGU0 -> IGCR -> IGP0 Setting
    SCU_IGCR0.U &= ~(0x3 << IGP0_BIT_LSB_IDX);

    SCU_IGCR0.U |= 0x1 << IGP0_BIT_LSB_IDX;

    // SRC Interrupt Setting
    SRC_SCU_SCU_ERU0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_SCU_SCU_ERU0.U |= 0x0A << SRPN_BIT_LSB_IDX;

    SRC_SCU_SCU_ERU0.U &= ~(0x3 << TOS_BIT_LSB_IDX);

    SRC_SCU_SCU_ERU0.U |= 1 << SRE_BIT_LSB_IDX;
}

void initCCU60(void)
{
    // Password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);

    // Modify Access to clear ENDINIT
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) & ~(1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

    // Enable CCY
    CCU60_CLC.U &= ~(1<<DISR_BIT_LSB_IDX);

    // Password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);

    // Modify Access to set ENDINIT
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

    // CCU60 T12 configurations
    while(CCU60_CLC.U & (1 << DISS_BIT_LSB_IDX) != 0);

    CCU60_TCTR0.U &= ~(0x7 << T12CLK_BIT_LSB_IDX);
    CCU60_TCTR0.U |= 0x2 << T12CLK_BIT_LSB_IDX;
    CCU60_TCTR0.U |= 0x1 << T12PRE_BIT_LSB_IDX;

    CCU60_TCTR0.U &= ~(0x1 << CTM_BIT_LSB_IDX);

    // interrupt per 1 sec
    CCU60_T12PR.U = 48828-1;  //(48828Hz / 2) - 1

    // Set Shadow value to Period Register
    CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;

    // Clear T12 counter register
    CCU60_T12.U = 0;

    CCU60_INP.U &= ~(0x3 << INPT12_BIT_LSB_IDX);
    CCU60_IEN.U |= 0x1 << ENT12PM_BIT_LSB_IDX; // Enable T12 interrupt


    //SRC setting for CCU60
    SRC_CCU6_CCU60_SR0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_CCU6_CCU60_SR0.U |= 0x0B << SRPN_BIT_LSB_IDX;

    SRC_CCU6_CCU60_SR0.U &= ~(0x3 << TOS_BIT_LSB_IDX);

    SRC_CCU6_CCU60_SR0.U |= 0x1 << SRE_BIT_LSB_IDX;

    // CCU60 T12 Counting start
    CCU60_TCTR4.U = 0x1 << T12RS_BIT_LSB_IDX;

}


void initADC(void)
{
    // Password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);



    // Modify Access to clear ENDINIT
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) & ~(1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

    // Enable VADC
    VADC_CLC.U &= ~(1<<DISR_BIT_LSB_IDX);

    // Password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);

    // Modify Access to set ENDINIT
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

    // VADC configurations
    while(VADC_CLC.U & (1 << DISS_BIT_LSB_IDX) != 0);

    VADC_G4_ARBPR.U |= 0x3 << PRIO0_BIT_LSB_IDX;  // set request source 0 as highest priority
    VADC_G4_ARBPR.U &= ~(0x1 << CSM0_BIT_LSB_IDX); // wait - for - start mode
    VADC_G4_ARBPR.U |= 0x1 << ASEN0_BIT_LSB_IDX; // Arbitration Source input 0 enable

    VADC_G4_QMR0.U &= ~(0x3 << ENGT_BIT_LSB_IDX);
    VADC_G4_QMR0.U |= 0x1 << ENGT_BIT_LSB_IDX;  // enable conversion request
    VADC_G4_QMR0.U |= 0x1 << FLUSH_BIT_LSB_IDX; // clear ADC queue

    VADC_G4_ARBCFG.U |= 0x3 << ANONC_BIT_LSB_IDX; // Set ADC Normal Operation Mode

    VADC_G4_ICLASS0.U &= ~(0x7 << CMS_BIT_LSB_IDX); // Class - How conversion is sensitive : Set conversion 12bit mode

    VADC_G4_CHCTR7.U &= ~(0x3 << ICLSEL_BIT_LSB_IDX); // Set group-specific class 0 (ICLASS0)
    VADC_G4_CHCTR7.U &= ~(0xF << RESREG_BIT_LSB_IDX); // Store result in group result register G7RES0
    VADC_G4_CHCTR7.U |= 0x1 << RESPOS_BIT_LSB_IDX; // Store results as right-aligned

    VADC_G4_CHASS.U |= 0x1 << ASSCH7_BIT_LSB_IDX; // Set channel as a priority channel
}


void VADC_startConversion(void)
{
    VADC_G4_QINR0.U |= 0x07; // Set Number of Request Channel as 7
    VADC_G4_QMR0.U |= 0x1 << TREV_BIT_LSB_IDX; // Generate conversion trigger
}

unsigned int VADC_readResult(void)
{
    unsigned int result;
    while((VADC_G4_RES0.U & (0x1 << VF_BIT_LSB_IDX)) == 0); // wait until read available
    result = VADC_G4_RES0.U & (0xFFF << RESULT_BIT_LSB_IDX); // read ADC value

    return result;
}
/*
__interrupt(0x0B) __vector_table(0)
void CCU60_T12_ISR(void)
{
    P10_OUT.U ^= 0x1 << P2_BIT_LSB_IDX;
}
*/
/*
__interrupt(0x0A) __vector_table(0)
void ERU0_ISR(void)
{
        if((P02_IN.U & (0x1 << P1_BIT_LSB_IDX)) == 0)
        {
            P10_OUT.B.P1 = 0x1;
            CCU60_T12PR.U = 12207-1;
            CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;
        }
        else
        {
            P10_OUT.B.P1 = 0x0;
            CCU60_T12PR.U = 24414-1;
            CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;
        }
}
*/

/*
__interrupt(0x0B) __vector_table(0)
void CCU60_T12_ISR(void)
{
    static int num = 0;
    if (num == 0)
    {
        P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
        P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
        P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);
    }

    else if (num == 1)
    {
        P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
        P10_OUT.U |= 0x1 << P5_BIT_LSB_IDX;
        P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);
    }

    else
    {
        P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
        P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
        P10_OUT.U |= 0x1 << P3_BIT_LSB_IDX;
    }
    num++;
    num %= 3;
}
*/

int num = 0;

__interrupt(0x0A) __vector_table(0)
void ERU0_ISR(void)
{
        static int flag = 0;
        if (flag == 0)
        {
            P10_OUT.B.P1 = 0x1;
            flag = 1;
            num++;
        }
        else
        {
            P10_OUT.B.P1 = 0x0;
            flag = 0;
            num--;
        }
}


/*
__interrupt(0x0A) __vector_table(0)
void ERU0_ISR(void)
{
        if((P02_IN.U & (0x1 << P1_BIT_LSB_IDX)) == 0)
        {
            P10_OUT.B.P1 = 0x1;
            CCU60_T12PR.U = 12207-1;
            CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;
        }
        else
        {
            P10_OUT.B.P1 = 0x0;
            CCU60_T12PR.U = 24414-1;
            CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;
        }
}
*/


IfxCpu_syncEvent g_cpuSyncEvent = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    initERU();
    initCCU60();
    //initLED();
    initRGBLED();
    initPWMLED();
    initADC();
    initGTM();
    initButton();

    GTM_TOM0_TGC0_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX; // trigger update request signal
    GTM_TOM0_TGC1_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX;
    unsigned short duty = 0;
    unsigned short value = 0;
    while(1)
    {
        VADC_startConversion();
        unsigned int adcResult = VADC_readResult();

        if (num = 0)
        {
            duty = 12500 * adcResult / 4096;
            GTM_TOM0_CH1_SR1.U = duty;
            GTM_TOM0_CH2_SR1.U = duty;
            GTM_TOM0_CH3_SR1.U = duty;
            GTM_TOM0_CH15_SR1.U = duty;
            value = duty;
        }

        else
        {
            GTM_TOM0_CH1_SR1.U = value;
            GTM_TOM0_CH2_SR1.U = value;
            GTM_TOM0_CH3_SR1.U = value;
            GTM_TOM0_CH15_SR1.U = value;


        }

        /*
        for(unsigned int i = 0; i < 100; i++);

        if (adcResult >= 3096)
        {
            P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
            P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);
            GTM_TOM0_CH1_SR1.U = 0;
        }



        else if (adcResult >= 2048)
        {
            P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
            P10_OUT.U |= 0x1 << P5_BIT_LSB_IDX;
            P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);
            GTM_TOM0_CH1_SR1.U = 1000;
        }

        else if (adcResult >= 1024)
        {
            P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U |= 0x1 << P3_BIT_LSB_IDX;
            GTM_TOM0_CH1_SR1.U = 7000;
        }

        else
        {
            P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
            P10_OUT.U |= 0x1 << P5_BIT_LSB_IDX;
            P10_OUT.U |= 0x1 << P3_BIT_LSB_IDX;
            GTM_TOM0_CH1_SR1.U = 12500;
        }
        */


    }

    return (1);
}
