/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxCcu6_reg.h"
#include "IfxVadc_reg.h"
#include "IfxGtm_reg.h"

// Port registers
#define PC1_BIT_LSB_IDX         11
#define PC2_BIT_LSB_IDX         19
#define PC3_BIT_LSB_IDX         27
#define PC5_BIT_LSB_IDX         11
#define PC7_BIT_LSB_IDX         27
#define P1_BIT_LSB_IDX          1
#define P2_BIT_LSB_IDX          2
#define P3_BIT_LSB_IDX          3
#define P5_BIT_LSB_IDX          5
#define P7_BIT_LSB_IDX          7

// SCU REGISTER
#define LCK_BIT_LSB_IDX         1
#define ENDINIT_BIT_LSB_IDX     0
#define EXIS0_BIT_LSB_IDX       4
#define FEN0_BIT_LSB_IDX        8
#define REN0_BIT_LSB_IDX        9
#define EIEN0_BIT_LSB_IDX       11
#define INP0_BIT_LSB_IDX        12
#define IGP0_BIT_LSB_IDX        14

// SRC REGISTERS
#define SRPN_BIT_LSB_IDX        0
#define TOS_BIT_LSB_IDX         11
#define SRE_BIT_LSB_IDX         10

// CCU60 REGISTERS
#define DISS_BIT_LSB_IDX        1
#define DISR_BIT_LSB_IDX        0
#define CTM_BIT_LSB_IDX         7
#define T12PRE_BIT_LSB_IDX      3
#define T12CLK_BIT_LSB_IDX      0
#define T12STR_BIT_LSB_IDX      6
#define T12RS_BIT_LSB_IDX       1
#define INPT12_BIT_LSB_IDX      10
#define ENT12PM_BIT_LSB_IDX     7

// VADC registers
#define ANONC_BIT_LSB_IDX       0
#define ASEN0_BIT_LSB_IDX       24
#define CSM0_BIT_LSB_IDX        3
#define PRIO0_BIT_LSB_IDX       0
#define CMS_BIT_LSB_IDX         8
#define FLUSH_BIT_LSB_IDX       10
#define TREV_BIT_LSB_IDX        9
#define ENGT_BIT_LSB_IDX        0
#define RESPOS_BIT_LSB_IDX      21
#define RESREG_BIT_LSB_IDX      16
#define ICLSEL_BIT_LSB_IDX      0
#define VF_BIT_LSB_IDX          31
#define RESULT_BIT_LSB_IDX      0
#define ASSCH7_BIT_LSB_IDX      7

// GTM registers
#define SEL7_BIT_LSB_IDX        14
#define EN_FXCLK_BIT_LSB_IDX    22
#define FXCLK_SEL_BIT_LSB_IDX   0

// GTM - TOM0 registers
#define UPEN_CTRL1_BIT_LSB_IDX  18
#define HOST_TRIG_BIT_LSB_IDX   0
#define ENDIS_CTRL1_BIT_LSB_IDX 2
#define OUTEN_CTRL1_BIT_LSB_IDX 2
#define CLK_SRC_SR_BIT_LSB_IDX  12
#define OSM_BIT_LSB_IDX         26
#define TRIGOUT_BIT_LSB_IDX     24
#define SL_BIT_LSB_IDX          11


IfxCpu_syncEvent g_cpuSyncEvent = 0;

                                // 함수 선언부
void initCCU60(void);
void initERU(void);
void initLED(void);
void initButton(void);
void initRGBLED(void);
void initVADC(void);
void initGTM(void);
void initBuzzer(void);

void PW_ULK(void);
void VADC_startConversion(void);
unsigned int VADC_readResult(void);

                                // Interrupt 선언부
/*
// 버튼 활성화
__interrupt(0x0A)   __vector_table(0) // interrupt 발생 시 호출되는 함수 설정
void ERU0_ISR(void);
*/

// 클락 활성화
__interrupt(0x0B)   __vector_table(0) // interrupt 발생 시 호출되는 함수 설정
void CCU60_T12_ISR(void);

// 변수 선언
unsigned int adcResult;
unsigned short duty = 0;


int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
                                // ***Init 활성화 부분
    //initERU();
    initCCU60();
    initLED();  // 기존 initLED 함수랑은 다름 (PWM)
    initRGBLED();
    initVADC();
    initGTM();
    //initButton();

    // 최초 한 번 설정을 해두면 된다.
    GTM_TOM0_TGC0_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX;  // trigger update request signal
    GTM_TOM0_TGC1_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX;  // trigger update request signal


    // unsigned char pre = 1, cur = 1;

    while(1)
    {
        // 8. LED PWM
        VADC_startConversion();
        adcResult = VADC_readResult();
        for(unsigned int i = 0 ; i < 100 ; i++);

        // 보충 lab : 가변저항값에 따라 연속적인 LED Dimming
        duty = 12500 * adcResult / 4096;
        GTM_TOM0_CH2_SR1.U = duty;
        GTM_TOM0_CH3_SR1.U = duty;
        GTM_TOM0_CH15_SR1.U = duty;

        /*
        if( adcResult >= 3096)
        {
            P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
            P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 0;
        }
        else if( adcResult >= 2048)
        {
            P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
            P10_OUT.U |= (0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 1000;
        }
        else if( adcResult >= 1024)
        {
            P02_OUT.U &= ~(0x1 << P7_BIT_LSB_IDX);
            P10_OUT.U &= ~(0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U |= (0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 7000;
        }
        else
        {
            P02_OUT.U |= 0x1 << P7_BIT_LSB_IDX;
            P10_OUT.U |= (0x1 << P5_BIT_LSB_IDX);
            P10_OUT.U |= (0x1 << P3_BIT_LSB_IDX);

            GTM_TOM0_CH1_SR1.U = 12500;
        }
        */




    }
    return (1);
}

                    /*         init            */
void initButton(void)
{
    P02_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);

    P02_IOCR0.U |= 0x02 << PC1_BIT_LSB_IDX;
}

void initLED(void)
{
    // RESET P10_IOCR0 PC1,2
    P10_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);
    P10_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX);

    // GPIO 출력모드를 GTM 생성 출력으로 설정
    P10_IOCR0.U |= (0x11 << PC1_BIT_LSB_IDX);
    P10_IOCR0.U |= (0x10 << PC2_BIT_LSB_IDX);

    /* SET P10.1,2 push-pull general output
    P10_IOCR0.U |= (0x10 << PC1_BIT_LSB_IDX);
    P10_IOCR0.U |= (0x10 << PC2_BIT_LSB_IDX);
    */
}

void initRGBLED(void)
{
    // reset port IOCR regist
    P02_IOCR4.U &= ~(0x1F << PC7_BIT_LSB_IDX);
    P10_IOCR4.U &= ~(0x1F << PC5_BIT_LSB_IDX);
    P10_IOCR0.U &= ~(0x1F << PC3_BIT_LSB_IDX);

    // set port as general purpose output
    P02_IOCR4.U |= (0x10 << PC7_BIT_LSB_IDX);
    P10_IOCR4.U |= (0x10 << PC5_BIT_LSB_IDX);
    P10_IOCR0.U |= (0x10 << PC3_BIT_LSB_IDX);
}

// VADC (가변) 설정
void initVADC(void)
{
    // PW Access to unlock SCU_WDTSCON0
    PW_ULK();

    // Enable VADC [CLC 변경]
    VADC_CLC.U &= ~(1 << DISR_BIT_LSB_IDX);

    // Password Access to unlock SCU_WDTSCON0
    PW_ULK();

    // VADC configurations
    while((VADC_CLC.U & (1 << DISS_BIT_LSB_IDX)) != 0); // ENABLE까지 대기

    VADC_G4_ARBPR.U |= 0x3 << PRIO0_BIT_LSB_IDX;    // Request Source 우선순위 지정
    VADC_G4_ARBPR.U &= ~(0x1 << CSM0_BIT_LSB_IDX);  // Wait-for-start mode
    VADC_G4_ARBPR.U |= 0x1 << ASEN0_BIT_LSB_IDX;

    VADC_G4_QMR0.U &= ~(0x3 << ENGT_BIT_LSB_IDX);
    VADC_G4_QMR0.U |= 0x1 << ENGT_BIT_LSB_IDX;      // conversion request Enable
    VADC_G4_QMR0.U |= 0x1 << FLUSH_BIT_LSB_IDX;     // clear ADC queue

    VADC_G4_ARBCFG.U |= 0x3 << ANONC_BIT_LSB_IDX;   // ADC normal operation

    VADC_G4_ICLASS0.U &= ~(0x7 << CMS_BIT_LSB_IDX); // Class 0 Standard Conversion (12 bits)

    // VADC Group 4 Channel 7 Configuration
    VADC_G4_CHCTR7.U |= 0x1 << RESPOS_BIT_LSB_IDX;      // result right-aligned
    VADC_G4_CHCTR7.U &= ~(0xF << RESREG_BIT_LSB_IDX);   // store result
    VADC_G4_CHCTR7.U &= ~(0x3 << ICLSEL_BIT_LSB_IDX);   // class 0

    VADC_G4_CHASS.U |= 0x1 << ASSCH7_BIT_LSB_IDX;
}

// ERU Interrupt 사용위한 설정
void initERU(void)
{
    // ERU setting
    // ~여기는 초기화
    SCU_EICR1.U &= ~(0x7 << EXIS0_BIT_LSB_IDX);     // EICR1 레지스터에서 사용할 곳[EXIS0] 설정 (1번째 영역)
    SCU_EICR1.U |=  (0x1 << EXIS0_BIT_LSB_IDX);

    // ETL setting
    SCU_EICR1.U |=  0x1 << FEN0_BIT_LSB_IDX;      // Push 버튼의 falling edge 활성화

    // 2 - 버튼 눌렀다 땔 때 반응하도록
    SCU_EICR1.U |=  0x1 << REN0_BIT_LSB_IDX;

    SCU_EICR1.U |=  0x1 << EIEN0_BIT_LSB_IDX;     // trigger enable 만들기

    // OGU - Output Gating Unit - Trigger 이벤트 조합하여 Request 출력 만드는 곳
    SCU_EICR1.U &= ~(0x7 << INP0_BIT_LSB_IDX);

    // IGCR - 입력되는 트리거 신호 연결
    SCU_IGCR0.U &= ~(0x3 << IGP0_BIT_LSB_IDX);
    SCU_IGCR0.U |=  (0x1 << IGP0_BIT_LSB_IDX);

    // SRC Interrupt setting
    SRC_SCU_SCU_ERU0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_SCU_SCU_ERU0.U |=   0x0A << SRPN_BIT_LSB_IDX;       // 우선순위 및 고유 인식 설정

    SRC_SCU_SCU_ERU0.U &= ~(0x3  << TOS_BIT_LSB_IDX);       //  TOS 설정  - CPU0

    SRC_SCU_SCU_ERU0.U |=   1    << SRE_BIT_LSB_IDX;        // SRE 1로 설정 - interrupt enable
}

// 시간 설정
void initCCU60(void)
// unlock => ENDINIT clear => CCY Enable => SCU_WDTSCON0 unlock => ENDINIT set
// [최종 목표]CLC를 Enable로 하기 위해서 ENDINIT이 0이어야함 => ENDINIT을 풀기위해서는 LCK를 풀어야함
// => LCK를 풀기 위해 PW Access 해야함 => LCK 해제 - ENDINIT 값 바꿈 -> 바로 잠금
{
    // PW Access to unlock SCU_WDTSCON0
    PW_ULK();

    // Enable CCY [CLC 변경]
    CCU60_CLC.U &= ~(1 << DISR_BIT_LSB_IDX);

    // Password Access to unlock SCU_WDTSCON0
    PW_ULK();

        // ------- 위는 CLC - ENDINIT - LCK - PW - LCK - ENDINIT - CLC사용

    // CCU60 T12 configurations [DISS - 0 / DISR - 0 => Clock enable]
    while((CCU60_CLC.U & (1 << DISS_BIT_LSB_IDX)) != 0); // wait until CCU60 module enabled

    // 내부 clock 주파수 설정
    CCU60_TCTR0.U &= ~(0x7 << T12CLK_BIT_LSB_IDX);    // f_T12 = f_CCU6 / prescaler
    CCU60_TCTR0.U |= 0x2 << T12CLK_BIT_LSB_IDX;       // f_CCU6 = 50MHz, prescaler = 1024
    CCU60_TCTR0.U |= 0x1 << T12PRE_BIT_LSB_IDX;       // f_T12 = 48,828 Hz

    // T12 모듈에서 자동으로 초기화 시켜주기 위해 CTM 변경
    CCU60_TCTR0.U &= ~(0x1 << CTM_BIT_LSB_IDX);       // T12 auto reset when period match occur
        // --- 위는 T12 모듈 설정

    // 주기 T12PR 설정 [ 24414 - 1 => 48828 / 2 - 1==> 0.5s ]
    CCU60_T12PR.U = 24414 -1;                           // PM interrupt freq. = f_T12 / (T12PR + 1)

    // T12PR -> Write 값은 Period Shadow Register 머무름 -> T12STR이 1이 되면 Shadow Enable
    CCU60_TCTR4.U |= 0x1 << T12STR_BIT_LSB_IDX;         // Load T12PR from shadow regist

    // T1 counter 값 초기화 인데 이유는? => 후에 counter 증가 동작이므로 초기화 후 증가 필요
    CCU60_T12.U = 0;        // clear T12 counter regist

            // 타이머 인터럽트 발생 설정
        // CCU60_T12 PM interrupt setting
    // T12에서 발생한 INTERRUPT를 IR로 전달하기 위해 INPT12 영역 0
    CCU60_INP.U &= ~(0x3 << INPT12_BIT_LSB_IDX);
    // T12 모듈에서 Period Match 마다 enable하기 위해 ENT12PM 1로
    CCU60_IEN.U |= 0x1 << ENT12PM_BIT_LSB_IDX;


    // SRC setting for CCU60 - T12에서 발생한 INTERRUPT를 SR0에만 연결하기 위한 설정 (원래는 4개)
    SRC_CCU6_CCU60_SR0.U &= ~(0xFF << SRPN_BIT_LSB_IDX);
    SRC_CCU6_CCU60_SR0.U |= (0x0B << SRPN_BIT_LSB_IDX);

    // TOS - CPU0에서 처리 설정 => 0
    SRC_CCU6_CCU60_SR0.U &= ~(0x3 << TOS_BIT_LSB_IDX);

    // SRE - Interrupt를 enable로 설정 => 0
    SRC_CCU6_CCU60_SR0.U |= (0x1 << SRE_BIT_LSB_IDX);

    // CCU60 T12 COUNTING START
    CCU60_TCTR4.U = 0x1 << T12RS_BIT_LSB_IDX;
}

void initGTM(void)
{
    // PW Access to unlock SCU_WDTSCON0
    PW_ULK();

    // Enable GTM [CLC 변경]
    GTM_CLC.U &= ~(1 << DISR_BIT_LSB_IDX);

    // Password Access to unlock SCU_WDTSCON0
    PW_ULK();

    // GTM configurations
    while((GTM_CLC.U & (1 << DISS_BIT_LSB_IDX)) != 0); // ENABLE까지 대기

    // GTM clock config
    GTM_CMU_FXCLK_CTRL.U &= ~(0xF << FXCLK_SEL_BIT_LSB_IDX);        // input clock of CMU_FXCLK --> CMU_GCLK_EN
    GTM_CMU_CLK_EN.U |= 0x2 << EN_FXCLK_BIT_LSB_IDX;                // enable all CUM_FXCLK

    // GTM TOM0 PWM CONFIG
    GTM_TOM0_TGC0_GLB_CTRL.U |= 0x2 << UPEN_CTRL1_BIT_LSB_IDX;      // TOM ch 1 update enable
    GTM_TOM0_TGC0_ENDIS_CTRL.U |= 0x2 << ENDIS_CTRL1_BIT_LSB_IDX;   // enable ch 1 on update trigger
    GTM_TOM0_TGC0_OUTEN_CTRL.U |= 0x2 << OUTEN_CTRL1_BIT_LSB_IDX;   // enable ch1 output on update trigger

    GTM_TOM0_CH1_CTRL.U |= 0x1 << SL_BIT_LSB_IDX;
    GTM_TOM0_CH1_CTRL.U |= 0x1 << CLK_SRC_SR_BIT_LSB_IDX;
    GTM_TOM0_CH1_CTRL.U &= ~(0x1 << OSM_BIT_LSB_IDX);
    GTM_TOM0_CH1_CTRL.U &= ~(0x1 << TRIGOUT_BIT_LSB_IDX);

    GTM_TOUTSEL6.U &= ~(0x3 << SEL7_BIT_LSB_IDX);   // TOUT103 --> TOM0 ch 1

    // 보충 LAB => set TGC0 to enable GTM TOM0 CH 2, 3, 15
    GTM_TOM0_TGC0_GLB_CTRL.B.UPEN_CTRL2 |= 0x2;
    GTM_TOM0_TGC0_GLB_CTRL.B.UPEN_CTRL3 |= 0x2;
    GTM_TOM0_TGC1_GLB_CTRL.B.UPEN_CTRL7 |= 0x2;

    GTM_TOM0_TGC0_ENDIS_CTRL.B.ENDIS_CTRL2 |= 0x2;
    GTM_TOM0_TGC0_ENDIS_CTRL.B.ENDIS_CTRL3 |= 0x2;
    GTM_TOM0_TGC1_ENDIS_CTRL.B.ENDIS_CTRL7 |= 0x2;

    GTM_TOM0_TGC0_OUTEN_CTRL.B.OUTEN_CTRL2 |= 0x2;
    GTM_TOM0_TGC0_OUTEN_CTRL.B.OUTEN_CTRL3 |= 0x2;
    GTM_TOM0_TGC1_OUTEN_CTRL.B.OUTEN_CTRL7 |= 0x2;


    // 보충 LAB => set GTM TOM0 ch 11 - buzzer
    GTM_TOM0_TGC1_GLB_CTRL.B.UPEN_CTRL3    |= 0x2;      // TOM ch 1 update enable
    GTM_TOM0_TGC1_ENDIS_CTRL.B.ENDIS_CTRL3 |= 0x2;   // enable ch 1 on update trigger
    GTM_TOM0_TGC1_OUTEN_CTRL.B.OUTEN_CTRL3 |= 0x2;   // enable ch1 output on update trigger

    GTM_TOM0_CH1_SR0.U = 12500 - 1;         // PWM FREQ. = 6250 kHz / 12500 = 500 Hz [2ms] => 1ms : 6250 | 2ms : 12500
    GTM_TOM0_CH1_SR1.U = 1250 - 1;          // Duty Cycle = 1250 / 12500 = 10 %
                                            // 103 = 16 * 6 + 7
    // TOM 0_11
    GTM_TOM0_CH11_CTRL.B.SL = 0x1;
    GTM_TOM0_CH11_CTRL.B.CLK_SRC_SR = 0x1;
    GTM_TOM0_CH11_SR0.B.SR0 = 12500 - 1;         // PWM FREQ. = 6250 kHz / 12500 = 500 Hz [2ms] => 1ms : 6250 | 2ms : 12500
    GTM_TOM0_CH11_SR1.B.SR1 = 1250 - 1;          // Duty Cycle = 1250 / 12500 = 10 %

    // TOUT pin selection
    GTM_TOUTSEL0.B.SEL3 = 0x0;
}

void initBuzzer(void)
{
    P02_IOCR0.B.PC3 = 0x11;
}

                    /*         함  수            */
void PW_ULK(void)
{
    // PW Access to unlock SCU_WDTSCON0
            // ^를 통해 원래대로 바꿈 -> PW는 반전되어 받으므로
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);  // unlock 대기

    // Modify Access to clear ENDINIT => Mask 작업
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) & ~(1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);  // lock 대기
}

void ERU0_ISR(void)
{
    // 0
    /*
    P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX; // 눌렸을 경우 반짝이게 ==>
    */

    // 1
    /*
    P10_OUT.U ^= 0x1 << P1_BIT_LSB_IDX;
    for(uint32 i = 0; i <300000; i++);   // sw DELAY;
    P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX); // 눌렸을 경우 반짝이게
    */

    // 2는 init-setting ㄱㄱ

    // 3
    /*
    unsigned char a,b,c;

    a = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(uint32 i = 0; i <10000000; i++);   // sw DELAY;

    b = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(uint32 i = 0; i <10000000; i++);   // sw DELAY;

    c = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
    for(uint32 i = 0; i <10000000; i++);   // sw DELAY;

    if ( a == 0 && b == 0 && c == 0)
    {
        P10_OUT.U |= 0x1 << P1_BIT_LSB_IDX;
        for(uint32 i = 0; i <5000000; i++);   // sw DELAY;
        P10_OUT.U &= ~(0x1 << P1_BIT_LSB_IDX); // 눌렸을 경우 반짝이게
    }
    */

    // 보충 lab

    if((P02_IN.U & (0x1 << P1_BIT_LSB_IDX)) == 0)   // BUTTON PUSHED
    {
        P10_OUT.B.P1 = 0x1;
        CCU60_T12PR.U = 12207 - 1;
        CCU60_TCTR4.U = 0x1 << T12STR_BIT_LSB_IDX;  // shadow register로 보내기
    }
    else    // Button released
    {
        P10_OUT.B.P1 = 0x0;
        CCU60_T12PR.U = 24414 - 1;
        CCU60_TCTR4.U = 0x1 << T12STR_BIT_LSB_IDX;
    }
}

void CCU60_T12_ISR(void){
    P10_OUT.U ^= 0x1 << P2_BIT_LSB_IDX; // 푸른 색 토글

    VADC_startConversion();
    adcResult = VADC_readResult();
}

void VADC_startConversion(void)
{
    VADC_G4_QINR0.U |= 0x07;

    VADC_G4_QMR0.U |= 0x1 << TREV_BIT_LSB_IDX;
}

unsigned int VADC_readResult(void)
{
    unsigned int result;

    while((VADC_G4_RES0.U & (0x1 << VF_BIT_LSB_IDX))  == 0);
    result = VADC_G4_RES0.U & (0xFFF << RESULT_BIT_LSB_IDX);

    return result;
}
