/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Cpu0_Main.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

unsigned int range_right;
unsigned int range_left;
unsigned char range_valid_flag_right = 0;
unsigned char range_valid_flag_left = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    initERUD2();
    //initERUD3();
    initPWM_LED();
    initVADC();
    initRGBLED();
    initButton();
    initBuzzer();
    initGTM();
    initConnect();

    initERURight();
    initERULeft();
    initCCU60();
    initCCU61();
    initUsonic();

    GTM_TOM0_TGC0_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX;       // trigger update request signal
    GTM_TOM0_TGC1_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX;       // trigger update request signal

    unsigned short duty = 0;

    while(1) {

        // VADC
        VADC_startConversion();                          // make ADC convert request
        unsigned int adcResult = VADC_readResult();      // if it finishes, get result
        duty = 12500 * adcResult / 4096;

        // Ultrasonic
        usonicTriggerRight();
        while(range_valid_flag_right == 0);

        usonicTriggerLeft();
        while(range_valid_flag_left == 0);

        if (range_left < 80)
            GTM_TOM0_CH2_SR1.U = (12500 - duty) * range_left / 40; // left -> blue
        else if (range_left < 40)
            GTM_TOM0_CH2_SR1.U = 0;
        else
            GTM_TOM0_CH2_SR1.U = 12500-duty;

        if (range_right < 80)
            GTM_TOM0_CH1_SR1.U = duty * range_right / 40; // right -> red
        else if (range_right < 40)
            GTM_TOM0_CH1_SR1.U = 0;
        else
            GTM_TOM0_CH1_SR1.U = duty;

    }
    return (1);
}
