/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Cpu0_Main.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;
extern unsigned int range_right;
extern unsigned int range_left;

int core2_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initButton();
    
    while(1)
    {
        unsigned char f, d, e;

        f = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
        for(unsigned int i = 0; i < 100; i++);

        d = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
        for(unsigned int i = 0; i < 100; i++);

        e = P02_IN.U & (0x1 << P1_BIT_LSB_IDX);
        for(unsigned int i = 0; i < 100; i++);

        // ACCELERATOR (button D2) is pushed
        if( f == 0 && d == 0 && e == 0 ) {

            if((P02_OUT.U & (0x1 << P7_BIT_LSB_IDX)) == (0x1 << P7_BIT_LSB_IDX)) { // if RED light is ON

                if(range_right < 40 || range_left < 40) {
                    // Forward Collision Warning
                    for(int i = 0; i < 4; i++) {
                        GTM_TOM0_CH11_SR0.B.SR0 = 6250000 / 987;
                        GTM_TOM0_CH11_SR1.B.SR1 = 3125000 / 987;
                        for(int i = 0; i < 2000000; i++);
                        GTM_TOM0_CH11_SR0.B.SR0 = 0;
                        GTM_TOM0_CH11_SR1.B.SR1 = 0;
                        for(int i = 0; i < 2000000; i++);
                    }
                }
            }
            else if((P10_OUT.U & (0x1 << P5_BIT_LSB_IDX)) == (0x1 << P5_BIT_LSB_IDX)) { // if GREEN light is ON

                // P00.3 (PIN31)
                P00_OUT.U &= ~(0x1 << P3_BIT_LSB_IDX);
                for(int i = 0; i < 10000; i++);
                P00_OUT.U |= 0x1 << P3_BIT_LSB_IDX;

            }
        }
        for (int i=0;i<1000000;i++);

    }
    return (1);
}
